import { listarIniciativas } from "/assets/js/services/iniciativasService.js";
import { getAppDownloadConfig } from "/assets/js/services/appDownloadConfig.js";

const esc=(value="")=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const clean=value=>String(value||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const image=item=>item.imagem_capa_url||"/assets/compartilhamento-logo.png";
const typeLabel=item=>item.tipo==="projeto"?"Projeto permanente":"Ação da comunidade";
let items=[],filter="all",term="";const root=document.getElementById("initiatives-grid"),status=document.getElementById("initiatives-status");
function summary(item){const text=clean(item.resumo);return /Exibir na listagem|Salvar iniciativa|Formas de ajuda/i.test(text)?"Conheça a história, o propósito e as formas de participar desta iniciativa.":text||"Conheça esta iniciativa divulgada pelo Eu Amo Urânia."}
function card(item){return `<a class="initiative-card" href="/preview/iniciativas/detalhe/?slug=${encodeURIComponent(item.slug)}"><span class="initiative-card-media"><img src="${esc(image(item))}" alt="${esc(item.titulo||"Iniciativa da comunidade")}" width="760" height="540" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='/assets/compartilhamento-logo.png';this.classList.add('is-fallback')"><span class="initiative-card-type">${esc(typeLabel(item))}</span></span><span class="initiative-card-copy"><h3>${esc(item.titulo||"Iniciativa")}</h3><p>${esc(summary(item))}</p><span class="initiative-card-footer"><span>Conhecer iniciativa</span>${item.destaque?"<em>Destaque</em>":"<b>→</b>"}</span></span></a>`}
function render(){const visible=items.filter(item=>(filter==="all"||item.tipo===filter)&&(!term||clean(`${item.titulo} ${item.resumo}`).toLocaleLowerCase("pt-BR").includes(term)));root.innerHTML=visible.length?visible.map(card).join(""):'<p class="initiative-empty">Nenhuma iniciativa encontrada.</p>';status.textContent=visible.length?`${visible.length} ${visible.length===1?"iniciativa encontrada":"iniciativas encontradas"}.`:""}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));render()}));document.getElementById("initiative-search")?.addEventListener("input",event=>{term=event.target.value.trim().toLocaleLowerCase("pt-BR");render()});
function chrome(){const header=document.querySelector(".site-header"),menu=document.getElementById("menu-principal"),toggle=header?.querySelector(".menu-toggle"),trigger=header?.querySelector(".search-trigger"),input=document.getElementById("header-search-input"),close=()=>{header?.classList.remove("search-open");trigger?.setAttribute("aria-expanded","false")};trigger?.addEventListener("click",()=>{menu?.classList.remove("is-open");toggle?.setAttribute("aria-expanded","false");header?.classList.add("search-open");trigger.setAttribute("aria-expanded","true");setTimeout(()=>input?.focus(),180)});toggle?.addEventListener("click",()=>{close();const open=toggle.getAttribute("aria-expanded")!=="true";toggle.setAttribute("aria-expanded",String(open));menu?.classList.toggle("is-open",open)});header?.querySelector(".header-search-close")?.addEventListener("click",close);document.getElementById("year").textContent=new Date().getFullYear();getAppDownloadConfig().then(app=>document.querySelectorAll("[data-app-download]").forEach(link=>link.href=app.googlePlayUrl||app.appStoreUrl||app.appPageUrl||"/app.html")).catch(()=>{})}
function renderHero(){const item=items[0];if(!item)return;const feature=document.getElementById("initiative-hero-feature"),heroImage=document.getElementById("initiative-hero-image"),heroTitle=document.getElementById("initiative-hero-title");feature.href=`/preview/iniciativas/detalhe/?slug=${encodeURIComponent(item.slug)}`;heroImage.onerror=()=>{heroImage.onerror=null;heroImage.src="/assets/compartilhamento-logo.png";heroImage.classList.add("is-fallback")};heroImage.src=image(item);heroImage.alt=item.titulo||"Iniciativa da comunidade";heroTitle.textContent=item.titulo||"Iniciativa da comunidade"}
async function init(){chrome();try{items=(await listarIniciativas()).sort((a,b)=>Number(Boolean(b.destaque))-Number(Boolean(a.destaque))||Number(a.ordem??9999)-Number(b.ordem??9999));renderHero();render()}catch(error){console.warn("Iniciativas:",error);status.textContent="Não foi possível carregar as iniciativas agora."}Promise.allSettled([import("/assets/js/pages/site-config-page.js"),import("/assets/js/pages/analytics-page.js"),import("/assets/js/pages/google-analytics-page.js"),import("/assets/js/pages/error-monitor.js")])}init();
