window.__previewSourceUrl=window.location.hostname==="htmlpreview.github.io"?decodeURIComponent(window.location.search.slice(1)):"";
function loadImageStyles(){const style=document.createElement("style");style.textContent=`.hero-visual > img{height:680px;aspect-ratio:auto;object-fit:cover;object-position:center 45%}@media(max-width:900px){.hero-visual > img{height:560px}}@media(max-width:620px){.hero-visual > img{height:400px}}`;document.head.appendChild(style)}
function loadPolishStyles(){if(document.querySelector('link[data-public-polish]'))return;const link=document.createElement("link");link.rel="stylesheet";link.dataset.publicPolish="true";const script=document.querySelector('script[src$="script.js"]');link.href=new URL("assets/css/public-polish.css",script?.src||location.origin+"/").href;document.head.appendChild(link)}
function updateAboutLinks(){document.querySelectorAll('a[href*="#sobre"]').forEach(link=>{if(window.__previewSourceUrl){const source=new URL(window.__previewSourceUrl),relative=source.pathname.includes("/news/")||source.pathname.includes("/eventos/")?"../quem-somos.html":"quem-somos.html";link.href=`https://htmlpreview.github.io/?${new URL(relative,source).href}`}else link.href="/quem-somos.html"})}
function setupPreviewNavigation(){if(!window.__previewSourceUrl)return;document.addEventListener("click",event=>{const link=event.target.closest("a");if(!link||link.target==="_blank")return;const href=link.getAttribute("href");if(!href||href.startsWith("#")||href.startsWith("mailto:")||href.startsWith("tel:")||href.includes("htmlpreview.github.io/?https://raw.githubusercontent.com/")||/^https?:\/\//i.test(href))return;event.preventDefault();const target=new URL(href,window.__previewSourceUrl);if(target.pathname.endsWith("news-details.html")&&target.search){target.hash=target.search.slice(1);target.search=""}window.location.href=`https://htmlpreview.github.io/?${target.href}`})}
function updateFooterYear(){const el=document.getElementById("year");if(el)el.textContent=new Date().getFullYear()}
function setupMenu(){const button=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");if(!button||!nav)return;const close=()=>{button.setAttribute("aria-expanded","false");nav.classList.remove("is-open")};button.addEventListener("click",()=>{const open=button.getAttribute("aria-expanded")!=="true";button.setAttribute("aria-expanded",String(open));nav.classList.toggle("is-open",open)});nav.addEventListener("click",e=>{if(e.target.closest("a"))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){close();button.focus()}});window.addEventListener("resize",()=>{if(innerWidth>900)close()})}
function setupCookieBanner(){const banner=document.getElementById("cookie-banner"),button=document.getElementById("accept-cookies");if(!banner||!button)return;try{if(!localStorage.getItem("cookieConsent"))banner.hidden=false;button.addEventListener("click",()=>{localStorage.setItem("cookieConsent","accepted");banner.hidden=true})}catch{banner.hidden=false;button.addEventListener("click",()=>{banner.hidden=true})}}
async function loadPublicModules(){const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js";for(const path of ["assets/js/pages/banners-page.js","assets/js/pages/eventos-page.js","assets/js/pages/analytics-page.js","assets/js/pages/destaques-page.js"]){try{await import(new URL(path,base).href)}catch(error){console.error("Módulo público:",error)}}}
loadImageStyles();loadPolishStyles();setupPreviewNavigation();
document.addEventListener("DOMContentLoaded",()=>{updateAboutLinks();updateFooterYear();setupMenu();setupCookieBanner();loadPublicModules()});
