window.__previewSourceUrl=window.location.hostname==="htmlpreview.github.io"?decodeURIComponent(window.location.search.slice(1)):"";
function updateAboutLinks(){document.querySelectorAll('a[href*="#sobre"]').forEach(link=>{if(window.__previewSourceUrl){const source=new URL(window.__previewSourceUrl),relative=source.pathname.includes("/news/")||source.pathname.includes("/eventos/")?"../quem-somos.html":"quem-somos.html";link.href=`https://htmlpreview.github.io/?${new URL(relative,source).href}`}else link.href="/quem-somos.html"})}
function setupPreviewNavigation(){if(!window.__previewSourceUrl)return;document.addEventListener("click",event=>{const link=event.target.closest("a");if(!link||link.target==="_blank")return;const href=link.getAttribute("href");if(!href||href.startsWith("#")||href.startsWith("mailto:")||href.startsWith("tel:")||href.includes("htmlpreview.github.io/?https://raw.githubusercontent.com/")||/^https?:\/\//i.test(href))return;event.preventDefault();const target=new URL(href,window.__previewSourceUrl);if(target.pathname.endsWith("news-details.html")&&target.search){target.hash=target.search.slice(1);target.search=""}window.location.href=`https://htmlpreview.github.io/?${target.href}`})}
function updateFooterYear(){const el=document.getElementById("year");if(el)el.textContent=new Date().getFullYear()}
function setupMenu(){const button=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");if(!button||!nav)return;const close=()=>{button.setAttribute("aria-expanded","false");nav.classList.remove("is-open")};button.addEventListener("click",()=>{const open=button.getAttribute("aria-expanded")!=="true";button.setAttribute("aria-expanded",String(open));nav.classList.toggle("is-open",open)});nav.addEventListener("click",e=>{if(e.target.closest("a"))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){close();button.focus()}});window.addEventListener("resize",()=>{if(innerWidth>900)close()})}
function setupCookieBanner(){let banner=document.getElementById("cookie-banner");if(!banner){banner=document.createElement("div");banner.id="cookie-banner";banner.className="cookie-banner";banner.hidden=true;banner.innerHTML='<p>Usamos cookies opcionais para medir a audiência. <a href="/politica-de-privacidade.html">Saiba mais</a></p><button id="accept-cookies">Aceitar</button>';document.body.append(banner)}else{const text=banner.querySelector("p");if(text)text.innerHTML='Usamos cookies opcionais para medir a audiência. <a href="/politica-de-privacidade.html">Saiba mais</a>'}const accept=banner.querySelector("#accept-cookies");if(!accept)return;accept.textContent="Aceitar";let reject=banner.querySelector("#reject-cookies");if(!reject){reject=document.createElement("button");reject.id="reject-cookies";reject.className="cookie-reject";reject.textContent="Recusar";accept.before(reject)}const choice=()=>{try{return localStorage.getItem("cookieConsent")}catch{return null}};banner.hidden=Boolean(choice());accept.addEventListener("click",()=>{try{localStorage.setItem("cookieConsent","accepted")}catch{}banner.hidden=true;window.dispatchEvent(new CustomEvent("cookie-consent:accepted"))});reject.addEventListener("click",()=>{try{localStorage.setItem("cookieConsent","declined")}catch{}banner.hidden=true;window.dispatchEvent(new CustomEvent("cookie-consent:declined"))})}
async function loadPublicModules(){const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js",path=location.pathname,home=path==="/"||path==="/index.html",paths=["assets/js/pages/site-config-page.js","assets/js/pages/banners-page.js","assets/js/pages/analytics-page.js","assets/js/pages/newsletter-public.js","assets/js/pages/google-analytics-page.js"];if(home||document.getElementById("eventos-list"))paths.push("assets/js/pages/eventos-page.js");if(home)paths.push("assets/js/pages/destaques-page.js");await Promise.allSettled(paths.map(async modulePath=>{try{await import(new URL(modulePath,base).href)}catch(error){console.error(`Módulo público (${modulePath}):`,error)}}))}
function schedulePublicModules(){const run=()=>loadPublicModules();if("requestIdleCallback"in window)requestIdleCallback(run,{timeout:1500});else setTimeout(run,300)}
function loadGlobalSearch(){const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js";import(new URL("assets/js/pages/global-search.js",base).href).catch(error=>console.error("Busca global:",error))}
setupPreviewNavigation();
document.addEventListener("DOMContentLoaded",()=>{updateAboutLinks();updateFooterYear();setupMenu();setupCookieBanner();loadGlobalSearch();schedulePublicModules()});
