window.__previewSourceUrl=window.location.hostname==="htmlpreview.github.io"?decodeURIComponent(window.location.search.slice(1)):"";
function updateAboutLinks(){document.querySelectorAll('a[href*="#sobre"]').forEach(link=>{if(window.__previewSourceUrl){const source=new URL(window.__previewSourceUrl),relative=source.pathname.includes("/news/")||source.pathname.includes("/eventos/")?"../quem-somos.html":"quem-somos.html";link.href=`https://htmlpreview.github.io/?${new URL(relative,source).href}`}else link.href="/quem-somos"})}
function setupPreviewNavigation(){if(!window.__previewSourceUrl)return;document.addEventListener("click",event=>{const link=event.target.closest("a");if(!link||link.target==="_blank")return;const href=link.getAttribute("href");if(!href||href.startsWith("#")||href.startsWith("mailto:")||href.startsWith("tel:")||href.includes("htmlpreview.github.io/?https://raw.githubusercontent.com/")||/^https?:\/\//i.test(href))return;event.preventDefault();const target=new URL(href,window.__previewSourceUrl);if(target.pathname.endsWith("news-details.html")&&target.search){target.hash=target.search.slice(1);target.search=""}window.location.href=`https://htmlpreview.github.io/?${target.href}`})}
function updateFooterYear(){const current=new Date().getFullYear(),years=current>2024?`2024–${current}`:"2024";document.querySelectorAll(".footer-bottom p").forEach(el=>{el.innerHTML=`&copy; ${years} Eu Amo Urânia. Todos os direitos reservados.<span class="footer-signature">Feito em Urânia, para Urânia.</span>`})}
function setupMenu(){const button=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");if(!button||!nav)return;const close=()=>{button.setAttribute("aria-expanded","false");nav.classList.remove("is-open")};button.addEventListener("click",()=>{const open=button.getAttribute("aria-expanded")!=="true";button.setAttribute("aria-expanded",String(open));nav.classList.toggle("is-open",open)});nav.addEventListener("click",e=>{if(e.target.closest("a"))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){close();button.focus()}});window.addEventListener("resize",()=>{if(innerWidth>900)close()})}
function setupCookieBanner(){let banner=document.getElementById("cookie-banner");if(!banner){banner=document.createElement("div");banner.id="cookie-banner";banner.className="cookie-banner";banner.hidden=true;banner.innerHTML='<p>Usamos cookies opcionais para medir a audiência e exibir anúncios do Google. <a href="/politica-de-privacidade">Saiba mais</a></p><button id="accept-cookies">Aceitar</button>';document.body.append(banner)}else{const text=banner.querySelector("p");if(text)text.innerHTML='Usamos cookies opcionais para medir a audiência e exibir anúncios do Google. <a href="/politica-de-privacidade">Saiba mais</a>'}const accept=banner.querySelector("#accept-cookies");if(!accept)return;accept.textContent="Aceitar";let reject=banner.querySelector("#reject-cookies");if(!reject){reject=document.createElement("button");reject.id="reject-cookies";reject.className="cookie-reject";reject.textContent="Recusar";accept.before(reject)}const choice=()=>{try{return localStorage.getItem("cookieConsentVersion")==="2"?localStorage.getItem("cookieConsent"):null}catch{return null}};banner.hidden=Boolean(choice());accept.addEventListener("click",()=>{try{localStorage.setItem("cookieConsent","accepted");localStorage.setItem("cookieConsentVersion","2")}catch{}banner.hidden=true;window.dispatchEvent(new CustomEvent("cookie-consent:accepted"))});reject.addEventListener("click",()=>{try{localStorage.setItem("cookieConsent","declined");localStorage.setItem("cookieConsentVersion","2")}catch{}banner.hidden=true;window.dispatchEvent(new CustomEvent("cookie-consent:declined"))})}
async function loadPublicModules(){const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js",path=location.pathname,home=path==="/"||path==="/index.html",paths=["assets/js/pages/error-monitor.js","assets/js/pages/site-config-page.js","assets/js/pages/banners-page.js","assets/js/pages/analytics-page.js","assets/js/pages/newsletter-public.js","assets/js/pages/google-analytics-page.js"];if(home||document.getElementById("eventos-list"))paths.push("assets/js/pages/eventos-page.js");if(home)paths.push("assets/js/pages/destaques-page.js","assets/js/pages/home-guide-page.js");await Promise.allSettled(paths.map(async modulePath=>{try{await import(new URL(modulePath,base).href)}catch(error){console.error(`Módulo público (${modulePath}):`,error)}}))}
function normalizePublicNavigation(){const nav=document.querySelector(".main-nav ul");if(!nav)return;const clean=location.pathname.replace(/\/+$/,"")||"/",path=location.pathname.replace(/\/+$/,"/"),items=[["In&iacute;cio","/",clean==="/"||clean==="/index.html"],["Ur&acirc;nia","/urania/",path==="/urania/"||path.endsWith("/urania.html")],["Guia","/guia",clean==="/guia"||path.endsWith("/guia.html")||path.startsWith("/guia/")],["Turismo","/turismo",clean==="/turismo"||path.endsWith("/turismo.html")||path.endsWith("/turismo-details.html")||path.startsWith("/turismo/")],["Not&iacute;cias","/news/",path.includes("/news/")||path.startsWith("/noticias/")||path.endsWith("/news-details.html")],["Melhores","/melhores-de-urania/",path.includes("/melhores-de-urania/")]];nav.innerHTML=items.map(([label,href,current])=>`<li><a href="${href}"${current?' aria-current="page"':""}>${label}</a></li>`).join("")};
window.normalizePublicNavigation=normalizePublicNavigation;
function schedulePublicModules(){const run=()=>loadPublicModules();if("requestIdleCallback"in window)requestIdleCallback(run,{timeout:1500});else setTimeout(run,300)}
function showGlobalSearchTrigger(){const list=document.querySelector(".main-nav ul");if(!list||list.querySelector("[data-open-global-search]"))return;list.insertAdjacentHTML("beforeend",'<li class="global-search-nav"><button class="global-search-trigger" type="button" data-open-global-search aria-haspopup="dialog" aria-controls="global-search-dialog" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m16.5 16.5 4 4"></path></svg><span>Buscar</span></button></li>')}
function loadGlobalSearch(){const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js";import(new URL("assets/js/pages/global-search.js",base).href).catch(error=>console.error("Busca global:",error))}
function loadPublicRedesign(){if(document.querySelector('link[data-public-redesign]'))return;const script=document.querySelector('script[src$="script.js"]'),base=script?.src||location.origin+"/script.js",link=document.createElement("link");link.rel="stylesheet";link.href=new URL("assets/css/public-redesign.css",base).href;link.dataset.publicRedesign="true";document.head.append(link)}
function setupNativeMapLinks(){const ua=navigator.userAgent||"",ios=/iPad|iPhone|iPod/i.test(ua)||navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1,android=/Android/i.test(ua);document.querySelectorAll("a[data-map-query]").forEach(link=>{const query=link.dataset.mapQuery?.trim();if(!query)return;const encoded=encodeURIComponent(query),fallback=link.dataset.mapFallback||`https://www.google.com/maps/search/?api=1&query=${encoded}`;link.dataset.mapFallback=fallback;if(android){link.href=`geo:0,0?q=${encoded}`;link.removeAttribute("target")}else if(ios){link.href=`https://maps.apple.com/?q=${encoded}`;link.removeAttribute("target")}else{link.href=fallback;link.target="_blank";link.rel="noopener"}})}
loadPublicRedesign();
setupPreviewNavigation();
document.addEventListener("DOMContentLoaded",()=>{normalizePublicNavigation();updateAboutLinks();updateFooterYear();showGlobalSearchTrigger();setupMenu();setupCookieBanner();setupNativeMapLinks();loadGlobalSearch();schedulePublicModules()});
window.addEventListener("guia:renderizado",setupNativeMapLinks);
window.addEventListener("turismo:renderizado",setupNativeMapLinks);
window.addEventListener("evento:renderizado",setupNativeMapLinks);
