import { fetchPublicRows, publicSupabaseConfigured } from "/assets/js/services/publicDataService.js";
import { definirMeta, textoPuro } from "/assets/js/utils.js";
import { sanitizeArticleHtml } from "/assets/js/security/sanitize-html.js";
import { responsiveImage } from "/assets/js/image-tools.js";
import { getAppDownloadConfig } from "/assets/js/services/appDownloadConfig.js";
import "/preview/guia/banners-preview.js";

const root=document.getElementById("agenda-tradition-details"),slug=new URLSearchParams(location.search).get("slug")||"";
const esc=(value="")=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const strip=value=>textoPuro(value||"").replace(/\s+/g," ").trim();
const safeImage=(value,options={})=>/^https?:\/\//i.test(value||"")||/^\/?assets\//i.test(value||"")?esc(responsiveImage(value,{width:1200,height:820,quality:80,...options})):"";
const icons={share:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.6 6.8-4.2M8.6 13.4l6.8 4.2"/></svg>',calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',pin:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>'};
function parseList(raw){if(Array.isArray(raw))return raw;if(typeof raw==="string"){try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[];}catch{return raw.split(/[\n,]/).map(value=>value.trim()).filter(Boolean);}}return [];}
function dateLabel(value){if(!value)return "Data a confirmar";const date=new Date(value);return Number.isNaN(date.getTime())?"Data a confirmar":new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long",year:"numeric",timeZone:"America/Sao_Paulo"}).format(date);}
function statusLabel(value){return ({rascunho:"Em preparação",anunciado:"Anunciado",confirmado:"Confirmado",acontecendo:"Acontecendo",encerrado:"Encerrado",cancelado:"Cancelado"})[value]||value||"Edição";}
function editionUrl(event,item){return `/preview/agenda/edicao/?slug=${encodeURIComponent(event.slug)}&ano=${encodeURIComponent(item.ano)}`;}
function editionCard(event,item){const image=safeImage(item.banner_url||item.cartaz_url||event.imagem_capa_url,{width:700,height:440,quality:76}),url=editionUrl(event,item);return `<article class="tradition-edition-card">${image?`<a href="${url}"><img src="${image}" alt="" width="700" height="440" loading="lazy" decoding="async"></a>`:""}<div><p>${esc(statusLabel(item.status))}</p><h3>${esc(item.titulo||`${event.nome} ${item.ano}`)}</h3><span>${esc(dateLabel(item.data_inicio))}${item.local?` · ${esc(item.local)}`:""}</span><a href="${url}">Ver edição <b aria-hidden="true">→</b></a></div></article>`;}
function galleryMarkup(event){const images=parseList(event.galeria_historica).map(item=>safeImage(typeof item==="string"?item:item?.url||item?.imagem_url,{width:760,height:560,quality:76})).filter(Boolean).slice(0,6);if(!images.length)return "";return `<section class="tradition-gallery"><header><p class="event-kicker">Memória da cidade</p><h2>Galeria histórica.</h2></header><div>${images.map((image,index)=>`<button type="button" data-gallery-image="${image}" aria-label="Ampliar foto ${index+1}"><img src="${image}" alt="${esc(`${event.nome}, registro histórico ${index+1}`)}" width="760" height="560" loading="lazy" decoding="async"></button>`).join("")}</div></section>`;}
function fact(label,value){return value?`<div><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`:"";}
async function load(){return (await fetchPublicRows("eventos_principais",{select:"*",slug:`eq.${slug}`,ativo:"eq.true",limit:"1"}))[0];}
async function render(){
  if(!publicSupabaseConfigured()||!slug){root.innerHTML='<p class="event-detail-status">Evento não encontrado.</p>';return;}
  try{
    const event=await load();if(!event){root.innerHTML='<p class="event-detail-status">Evento não encontrado.</p>';return;}
    const editions=await fetchPublicRows("eventos_edicoes",{select:"*",evento_id:`eq.${event.id}`,order:"ano.desc,data_inicio.desc"}).catch(()=>[]);
    const current=editions.find(item=>["anunciado","confirmado","acontecendo"].includes(item.status))||editions[0];
    const image=safeImage(event.imagem_capa_url),summary=strip(event.descricao_curta||event.historia_html)||`Conheça a história de ${event.nome} em Urânia.`,canonical=`https://euamourania.com.br/eventos/${encodeURIComponent(event.slug)}`;
    const historyHtml=sanitizeArticleHtml(event.historia_html||`<p>${esc(summary)}</p>`),shouldCollapse=strip(event.historia_html||summary).length>560;
    definirMeta({titulo:event.seo_titulo||`${event.nome} | Eventos em Urânia`,descricao:(event.seo_descricao||summary).slice(0,160),imagem:image||"/assets/compartilhamento-logo.png",url:canonical});
    const structured=document.createElement("script");structured.type="application/ld+json";structured.textContent=JSON.stringify({"@context":"https://schema.org","@type":"WebPage",name:event.nome,description:summary,url:canonical,image:image?new URL(image,location.origin).href:undefined});document.head.appendChild(structured);
    root.innerHTML=`<article class="tradition-detail"><nav class="event-breadcrumb" aria-label="Navegação estrutural"><a href="/preview/agenda/">Agenda</a><span>/</span><span aria-current="page">${esc(event.nome)}</span></nav><section class="event-detail-hero tradition-hero${image?" has-image":" no-image"}">${image?`<div class="event-detail-media"><img src="${image}" alt="${esc(event.nome)}" width="1200" height="820" fetchpriority="high" decoding="async"></div>`:"<div class=\"event-detail-media event-detail-placeholder\"><span>Tradição de Urânia</span></div>"}<div class="event-date-signature tradition-signature"><strong>Todo</strong><span>ano</span><small>${esc(event.periodo_aproximado||event.recorrencia||"Tradição")}</small></div><header class="event-detail-intro"><div class="event-detail-labels"><span>${esc(event.categoria||"Evento tradicional")}</span>${editions.length?`<b>${editions.length} ${editions.length===1?"edição":"edições"}</b>`:""}</div><h1>${esc(event.nome)}</h1><p>${esc(summary)}</p><div class="event-detail-actions">${current?`<a class="event-action primary" href="${editionUrl(event,current)}"><span>Ver edição ${esc(current.ano)}</span></a>`:""}<a class="event-action" href="#edicoes">${icons.calendar}<span>Ver edições</span></a><button class="event-icon-action" type="button" data-share-event aria-label="Compartilhar evento">${icons.share}</button></div></header></section>
      <section class="tradition-overview"><div><p class="event-kicker">Sobre o evento</p><h2>Uma tradição de Urânia.</h2><div id="tradition-story" class="tradition-story${shouldCollapse?" is-collapsed":""}">${historyHtml}</div>${shouldCollapse?'<button class="tradition-read-more" type="button" aria-expanded="false" aria-controls="tradition-story"><span>Ver mais</span><b aria-hidden="true">↓</b></button>':""}</div><aside><p class="event-kicker">Informações</p><h2>De geração em geração.</h2>${fact("Recorrência",event.recorrencia)}${fact("Período",event.periodo_aproximado)}${fact("Local tradicional",event.local_tradicional)}${fact("Organização",event.organizador)}</aside></section>
      <section id="edicoes" class="tradition-editions"><header><div><p class="event-kicker">Histórico</p><h2>Edições do evento.</h2></div><p>Programações, registros e informações de cada ano.</p></header>${editions.length?`<div class="tradition-editions-grid">${editions.map(item=>editionCard(event,item)).join("")}</div>`:'<p class="tradition-empty">As edições deste evento ainda serão cadastradas.</p>'}</section>${galleryMarkup(event)}</article>`;
    root.querySelector("[data-share-event]")?.addEventListener("click",async eventButton=>{try{if(navigator.share){await navigator.share({title:event.nome,text:summary,url:canonical});return;}await navigator.clipboard.writeText(canonical);eventButton.currentTarget.classList.add("copied");}catch(error){if(error?.name!=="AbortError")location.href=`https://wa.me/?text=${encodeURIComponent(`${event.nome}: ${canonical}`)}`;}});
    root.querySelector(".tradition-read-more")?.addEventListener("click",eventButton=>{const button=eventButton.currentTarget,story=root.querySelector("#tradition-story"),expanded=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!expanded));story?.classList.toggle("is-collapsed",expanded);button.querySelector("span").textContent=expanded?"Ver mais":"Ver menos";});
  }catch(error){console.error(error);root.innerHTML='<p class="event-detail-status">Não foi possível carregar este evento.</p>';}
}
const header=document.querySelector(".site-header"),menu=document.getElementById("menu-principal"),menuButton=header?.querySelector(".menu-toggle"),searchTrigger=header?.querySelector(".search-trigger"),searchInput=document.getElementById("header-search-input");const closeSearch=()=>{header?.classList.remove("search-open");searchTrigger?.setAttribute("aria-expanded","false");};searchTrigger?.addEventListener("click",()=>{menu?.classList.remove("is-open");menuButton?.setAttribute("aria-expanded","false");header?.classList.add("search-open");searchTrigger.setAttribute("aria-expanded","true");setTimeout(()=>searchInput?.focus(),180);});menuButton?.addEventListener("click",()=>{closeSearch();const open=menuButton.getAttribute("aria-expanded")!=="true";menuButton.setAttribute("aria-expanded",String(open));menu?.classList.toggle("is-open",open);});header?.querySelector(".header-search-close")?.addEventListener("click",closeSearch);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeSearch();});document.getElementById("year").textContent=new Date().getFullYear();getAppDownloadConfig().then(app=>document.querySelectorAll("[data-app-download]").forEach(link=>{link.href=app.googlePlayUrl||app.appStoreUrl||app.appPageUrl||"/app.html";})).catch(()=>{});
function configureNewsletter(){const signup=document.querySelector(".newsletter-signup");if(!signup)return false;const title=signup.querySelector("h2"),description=signup.querySelector(".newsletter-box > div > p:last-child"),name=signup.querySelector('input[name="nome"]');if(title)title.textContent="Urânia direto no seu e-mail.";if(description)description.textContent="Receba notícias importantes, novidades da cidade e conteúdos do Eu Amo Urânia.";if(name){name.placeholder="Seu nome";name.required=true;}return true;}
render().then(()=>Promise.allSettled([import("/assets/js/pages/site-config-page.js"),import("/assets/js/pages/analytics-page.js"),import("/assets/js/pages/newsletter-public.js"),import("/assets/js/pages/google-analytics-page.js"),import("/assets/js/pages/smart-app-banner.js"),import("/assets/js/pages/error-monitor.js")])).then(()=>{if(configureNewsletter())return;const observer=new MutationObserver(()=>{if(configureNewsletter())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),10000);});
