import { getAppDownloadConfig } from "/assets/js/services/appDownloadConfig.js";

const base="/preview/melhores/";
const mark='<span class="award-wordmark" aria-hidden="true">Melhores <b>de Urânia</b></span>';
const header=`<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><a class="brand" href="/preview/home/" aria-label="Eu Amo Urânia — início"><img src="/assets/1505%20-%20Urania%20-%20Logo%20Horizontal%20-%201.png" alt="Eu Amo Urânia" width="188" height="55"></a><nav class="main-nav" id="menu-principal" aria-label="Navegação principal"><a href="/preview/home/">Início</a><a href="/preview/noticias/">Notícias</a><a href="/preview/guia/">Guia</a><a href="/preview/turismo/">Turismo</a><a href="/preview/agenda/">Agenda</a><a href="/preview/urania/">Urânia</a><a href="${base}" aria-current="page">Melhores</a></nav><form class="header-search-form" action="/buscar.html" method="get" role="search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.8"></circle><path d="m16 16 4.2 4.2"></path></svg><label class="sr-only" for="header-search-input">Buscar no Eu Amo Urânia</label><input id="header-search-input" name="q" type="search" placeholder="O que você procura em Urânia?" autocomplete="off" minlength="2" required><button class="header-search-submit" type="submit">Buscar</button><button class="header-search-close" type="button" aria-label="Fechar busca">×</button></form><div class="header-actions"><button class="search-trigger" type="button" aria-label="Pesquisar no Eu Amo Urânia" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.8"></circle><path d="m16 16 4.2 4.2"></path></svg><span>Buscar</span></button><a class="app-shortcut" data-app-download href="/app.html"><img src="/assets/viva-origem-colorido.svg" alt="" width="22" height="22"><span>Viva Urânia</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="menu-principal"><i></i><i></i><span class="sr-only">Abrir menu</span></button></div></header>`;
const footer=`<footer class="site-footer"><div class="container footer-main"><div class="footer-brand"><img src="/assets/1505%20-%20Urania%20-%20Logo%20Horizontal%20-%201.png" alt="Eu Amo Urânia" width="1687" height="369"><p>Feito em Urânia, para Urânia.</p></div><nav class="footer-links" aria-label="Navegação do rodapé"><a href="/preview/noticias/">Notícias</a><a href="/preview/guia/">Guia</a><a href="/preview/turismo/">Turismo</a><a href="/preview/agenda/">Agenda</a><a href="${base}">Melhores</a><a href="/quem-somos.html">Quem somos</a><a href="/divulgue">Publicidade</a><a href="/app.html">Viva Urânia</a></nav></div><div class="container footer-bottom"><span>© 2024–<b id="year"></b> Eu Amo Urânia.</span><nav aria-label="Informações legais"><a href="/termos-de-servico.html">Termos de serviço</a><a href="/politica-de-privacidade.html">Privacidade</a></nav></div></footer>`;
const demo="";
const button=(href,label)=>`<a class="award-primary" href="${href}">${label} <span>→</span></a>`;
const hub=current=>`<nav class="award-hub" aria-label="Páginas da edição"><a class="${current==='edition'?'is-current':''}" href="${base}edicao/">Visão geral</a><a class="${current==='voting'?'is-current':''}" href="${base}votacao/">Votação</a><a class="${current==='results'?'is-current':''}" href="${base}resultados/">Resultados</a><a class="${current==='method'?'is-current':''}" href="${base}metodologia/">Metodologia</a><a class="${current==='rules'?'is-current':''}" href="${base}regulamento/">Regulamento</a></nav>`;
const feature=(label="Próxima edição")=>`<aside class="award-feature"><small>${label}</small><h2>Melhores de Urânia</h2><p>Esta área recebe imagem, período e situação da edição cadastrada no painel.</p><div class="award-chips"><span class="is-open">Status da edição</span><span>Período oficial</span></div></aside>`;
const cards=()=>["Edição mais recente","Edição anterior","Primeira edição"].map((title,index)=>`<article class="award-card"><div class="award-card-media"><strong>${2026-index}</strong>${mark}</div><div class="award-card-body"><small>Edição</small><h3>${title}</h3><p>Status, datas e informações oficiais aparecem aqui quando uma edição é publicada.</p><a class="award-link" href="${base}edicao/">Ver edição <b>→</b></a></div></article>`).join("");
const categories=()=>["Categoria em destaque","Outra categoria","Categoria da comunidade"].map((title,index)=>`<a href="${base}categoria/"><span>0${index+1}</span><div><h3>${title}</h3><p>Conheça os indicados e as informações desta categoria.</p></div><b>→</b></a>`).join("");
const nominees=(vote=false)=>["Indicado 01","Indicado 02","Indicado 03"].map((name,index)=>`<article class="award-nominee-card"><span class="award-nominee-number">${String(index+1).padStart(2,"0")}</span><h3>${name}</h3><p>Descrição cadastrada para apresentar o participante.</p>${vote?'<button class="award-primary" type="button" disabled>Votar</button>':`<a class="award-link" href="${base}categoria-permanente/">Ver histórico <b>→</b></a>`}</article>`).join("");
const hero=(eyebrow,title,lead,panel=feature(),actions="")=>`<section class="award-hero"><div class="award-shell award-hero-grid"><div><p class="award-eyebrow">${eyebrow}</p><h1>${title}<span>.</span></h1><p class="award-lead">${lead}</p>${actions}</div>${panel}</div></section>`;
const section=(eyebrow,title,description,content,soft=false)=>`<section class="award-section${soft?' is-soft':''}"><div class="award-shell"><header class="award-section-head"><div><p class="award-eyebrow">${eyebrow}</p><h2>${title}</h2></div>${description?`<p>${description}</p>`:""}</header>${content}</div></section>`;

function home(){return `<main id="conteudo">${hero("Uma realização Eu Amo Urânia","Melhores de Urânia","Uma premiação anual para reconhecer empresas, profissionais, projetos e pessoas que fazem a cidade acontecer.",`<div>${demo}${feature("Próxima edição")}</div>`,`<div class="award-actions">${button("#edicoes","Ver edições")}<a class="award-link" href="#como-funciona">Como funciona <b>↓</b></a></div>`)}${section("Edições","Histórico da premiação.","Edições abertas, encerradas e arquivadas ficam reunidas aqui.",`<div class="award-editions" id="edicoes">${cards()}</div>`)}<div id="como-funciona">${section("Transparência","Como funciona.","Um processo simples, público e organizado.",`<div class="award-process"><article><span>01</span><h3>Preparação</h3><p>O portal define edição, categorias, regras e período oficial.</p></article><article><span>02</span><h3>Participação</h3><p>A comunidade indica e vota durante as fases abertas.</p></article><article><span>03</span><h3>Apuração</h3><p>Os votos são auditados antes da divulgação oficial.</p></article></div>`,true)}</div>${section("Dúvidas","Perguntas frequentes.","Informações claras sobre a premiação.",`<div class="award-faq"><details><summary>O que é o Melhores de Urânia?</summary><p>Uma premiação anual criada pelo Eu Amo Urânia para reconhecer quem contribui com a cidade.</p></details><details><summary>É preciso pagar para participar?</summary><p>Não. Participação, indicação ou vitória não dependem de pagamento.</p></details><details><summary>Como funciona a votação?</summary><p>As regras e o período são publicados na página oficial de cada edição.</p></details></div>`)}</main>`}
function edition(){return `<main id="conteudo">${hero("Edição do prêmio","Melhores de Urânia","A página central de cada edição reúne fase atual, categorias, indicados, votação, regras e resultados.",`<div>${feature("Edição atual")}</div>`)}<section class="award-section is-soft"><div class="award-shell">${hub("edition")}</div></section>${section("Categorias","Quem participa desta edição.","Cada categoria leva à sua lista oficial de indicados.",`<div class="award-category-list">${categories()}</div>`)}${section("Indicações da comunidade","Indique quem merece participar.","Quando a fase estiver aberta, o formulário oficial aparecerá nesta área.",`<div class="award-feature"><small>Fase da edição</small><h2>Indicações serão abertas pelo painel.</h2><p>Datas e condições serão informadas na página oficial da edição.</p></div>`,true)}</main>`}
function category(){return `<main id="conteudo">${hero("Melhores de Urânia","Categoria em destaque","Conheça os participantes oficiais desta categoria na edição selecionada.",`<div>${demo}${feature("Categoria da edição")}</div>`)}${section("Indicados","Participantes da categoria.","A ordem e as informações são definidas pelos dados oficiais.",`<div class="award-nominee-grid">${nominees()}</div>`)}</main>`}
function permanent(){return `<main id="conteudo">${hero("Histórico da categoria","Categoria em destaque","Uma visão permanente da presença desta categoria ao longo das edições.",`<div>${demo}${feature("Histórico permanente")}</div>`)}${section("Edições","Participação ao longo dos anos.","Resultados e participantes ficam preservados por edição.",`<div class="award-years">${[2026,2025,2024].map((year,index)=>`<article class="award-year"><strong>${year}</strong><h3>${index?'Participação registrada':'Edição mais recente'}</h3><p>Indicados e resultado oficial desta categoria.</p><a class="award-link" href="${base}resultados/">Ver resultado <b>→</b></a></article>`).join("")}</div>`)}</main>`}
function voting(){return `<main id="conteudo">${hero("Votação popular","Escolha seus favoritos","A votação mantém a estrutura atual por categorias, com seleção clara e confirmação do voto.",`<div>${feature("Votação popular")}</div>`)}<section class="award-section is-soft"><div class="award-shell">${hub("voting")}</div></section>${section("Votação","Categoria em destaque.","Selecione uma categoria e escolha um participante.",`<div class="award-vote-layout"><nav class="award-vote-nav"><button class="is-active">Categoria em destaque</button><button>Outra categoria</button><button>Categoria da comunidade</button></nav><div class="award-vote-content"><h2>Categoria em destaque</h2><p>Escolha apenas um indicado nesta categoria.</p><div class="award-nominee-grid">${nominees(true)}</div><p class="award-vote-preview-note">A votação estará disponível durante o período oficial.</p></div></div>`)}</main>`}
function results(){return `<main id="conteudo">${hero("Resultado oficial","Vencedores da edição","A página preserva o resultado publicado e o histórico de cada categoria.",`<div>${feature("Resultado oficial")}</div>`)}<section class="award-section is-soft"><div class="award-shell">${hub("results")}</div></section>${section("Vencedores","Resultado oficial publicado.","Confira os vencedores divulgados em cada categoria.",`<div>${["Categoria em destaque","Outra categoria","Categoria da comunidade"].map((name,index)=>`<article class="award-winner"><span class="award-place">${index+1}º</span><div><small>${name}</small><h3>Nome do vencedor</h3></div><strong>Resultado oficial</strong></article>`).join("")}</div>`)}</main>`}
function documentPage(type){const method=type==="method",name=method?"Metodologia":"Regulamento";return `<main id="conteudo">${hero(name,name+" do prêmio","Critérios, etapas e compromissos apresentados de forma clara para toda a comunidade.",`<div>${demo}${feature(name+" oficial")}</div>`)}<section class="award-section is-soft"><div class="award-shell">${hub(type)}</div></section><section class="award-section"><article class="award-shell award-document"><nav class="award-document-nav"><a href="#objetivo">Objetivo</a><a href="#participacao">Participação</a><a href="#apuracao">Apuração</a></nav><p>Este espaço mantém o conteúdo oficial cadastrado no painel, com leitura confortável e hierarquia editorial.</p><h2 id="objetivo">1. Objetivo</h2><p>Apresentar os princípios e procedimentos da premiação Melhores de Urânia.</p><h2 id="participacao">2. Participação</h2><p>As condições, prazos e critérios de cada edição são publicados de maneira transparente.</p><ul><li>Participação gratuita conforme as regras oficiais.</li><li>Publicidade não garante indicação, voto ou vitória.</li><li>As datas são definidas para cada edição.</li></ul><h2 id="apuracao">3. Apuração</h2><p>Os votos são consolidados e verificados antes da publicação do resultado definitivo.</p></article></section></main>`}

const renderers={home,edition,category,permanent,voting,results,method:()=>documentPage("method"),rules:()=>documentPage("rules")};
const app=document.getElementById("awards-preview-app"),page=document.body.dataset.awardsPage||"home";app.innerHTML=header+(renderers[page]||home)()+footer;
const siteHeader=document.querySelector(".site-header"),menu=document.getElementById("menu-principal"),menuButton=siteHeader?.querySelector(".menu-toggle"),searchTrigger=siteHeader?.querySelector(".search-trigger"),searchInput=document.getElementById("header-search-input");
const closeSearch=()=>{siteHeader?.classList.remove("search-open");searchTrigger?.setAttribute("aria-expanded","false")};searchTrigger?.addEventListener("click",()=>{menu?.classList.remove("is-open");menuButton?.setAttribute("aria-expanded","false");siteHeader?.classList.add("search-open");searchTrigger.setAttribute("aria-expanded","true");setTimeout(()=>searchInput?.focus(),180)});menuButton?.addEventListener("click",()=>{closeSearch();const open=menuButton.getAttribute("aria-expanded")!=="true";menuButton.setAttribute("aria-expanded",String(open));menu?.classList.toggle("is-open",open)});siteHeader?.querySelector(".header-search-close")?.addEventListener("click",closeSearch);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeSearch()});document.getElementById("year").textContent=new Date().getFullYear();
getAppDownloadConfig().then(config=>{const href=config.googlePlayUrl||config.appStoreUrl||config.appPageUrl||"/app.html";document.querySelectorAll("[data-app-download]").forEach(link=>link.href=href)}).catch(()=>{});Promise.allSettled([import("/assets/js/pages/site-config-page.js"),import("/assets/js/pages/analytics-page.js"),import("/assets/js/pages/google-analytics-page.js"),import("/assets/js/pages/error-monitor.js")]);
