import { getSupabase } from '../assets/js/services/supabaseClient.js';
import { listarFormasAjuda, listarIniciativasAdmin, salvarFormaAjuda, salvarIniciativa, excluirFormaAjuda } from '../assets/js/services/iniciativasService.js';
import { gerarSlug } from '../assets/js/utils.js';

const esc = (v='') => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state = { items: [], selected: null, help: [], message: '' };
const blank = () => ({ tipo:'projeto', titulo:'', slug:'', resumo:'', descricao:'', imagem_capa_url:'', status:'rascunho', destaque:false, exibir_na_listagem:true, responsavel_nome:'', telefone:'', whatsapp:'', email:'', instagram:'', site_url:'', inicio_em:'', termina_em:'', iniciativa_pai_id:'' });
async function load() { state.items = await listarIniciativasAdmin(); if (state.selected?.id) { state.selected = state.items.find(x => x.id === state.selected.id) || null; state.help = state.selected ? await listarFormasAjuda(state.selected.id) : []; } render(); }
function form(item) { const projects = state.items.filter(x => x.tipo === 'projeto' && x.id !== item.id); return `<form id="initiative-form" class="admin-form"><div class="form-grid"><label>Tipo<select name="tipo"><option value="projeto" ${item.tipo==='projeto'?'selected':''}>Projeto permanente</option><option value="acao" ${item.tipo==='acao'?'selected':''}>Ação</option></select></label><label>Projeto pai (opcional)<select name="iniciativa_pai_id"><option value="">Ação independente</option>${projects.map(x=>`<option value="${x.id}" ${x.id===item.iniciativa_pai_id?'selected':''}>${esc(x.titulo)}</option>`).join('')}</select></label><label>Título<input required name="titulo" value="${esc(item.titulo)}"></label><label>Slug<input required name="slug" value="${esc(item.slug)}"></label><label>Status<select name="status">${['rascunho','publicado','encerrado','arquivado'].map(x=>`<option ${item.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Imagem de capa<input name="imagem_capa_url" value="${esc(item.imagem_capa_url)}"></label><label>Responsável<input name="responsavel_nome" value="${esc(item.responsavel_nome)}"></label><label>WhatsApp<input name="whatsapp" value="${esc(item.whatsapp)}"></label><label>Telefone<input name="telefone" value="${esc(item.telefone)}"></label><label>E-mail<input type="email" name="email" value="${esc(item.email)}"></label><label>Site<input type="url" name="site_url" value="${esc(item.site_url)}"></label><label>Instagram<input name="instagram" value="${esc(item.instagram)}"></label><label>Início<input type="datetime-local" name="inicio_em" value="${esc(item.inicio_em)}"></label><label>Encerramento<input type="datetime-local" name="termina_em" value="${esc(item.termina_em)}"></label></div><label>Resumo<textarea name="resumo">${esc(item.resumo)}</textarea></label><label>Sobre<textarea name="descricao">${esc(item.descricao)}</textarea></label><label><input type="checkbox" name="destaque" ${item.destaque?'checked':''}> Destacar</label><label><input type="checkbox" name="exibir_na_listagem" ${item.exibir_na_listagem?'checked':''}> Exibir na listagem</label><button class="admin-button">Salvar iniciativa</button></form>`; }
function helps() { if (!state.selected?.id) return ''; return `<section class="panel"><h3>Formas de ajuda</h3><p>Remova uma forma de ajuda para ocultá-la imediatamente do app e site após a atualização do banco.</p>${state.help.map(x=>`<article class="admin-list-row"><strong>${esc(x.titulo)}</strong><span>${esc(x.tipo)} · ${esc(x.recebedor_nome||'')}</span><button data-delete-help="${x.id}" class="admin-button secondary">Remover</button></article>`).join('')||'<p>Nenhuma forma cadastrada.</p>'}<form id="help-form" class="admin-form"><div class="form-grid"><label>Tipo<select name="tipo">${['pix','whatsapp','telefone','site','voluntariado','materiais','outro'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Título<input required name="titulo"></label><label>Valor / chave / link<input name="valor_publico"></label><label>Recebedor (obrigatório para Pix)<input name="recebedor_nome"></label><label>Ordem<input type="number" name="ordem" value="100"></label></div><label>Descrição<textarea name="descricao"></textarea></label><button class="admin-button">Adicionar forma de ajuda</button></form></section>`; }
function render() { const root = document.querySelector('#app-content'); if (!root) return; const item = state.selected || blank(); root.innerHTML = `<section class="admin-page"><header class="admin-page-header"><div><p class="eyebrow">Comunidade</p><h2>Iniciativas da Comunidade</h2><p>Cadastre projetos permanentes, ações independentes e formas de ajuda revisadas.</p></div><button id="new-initiative" class="admin-button">Nova iniciativa</button></header>${state.message?`<p class="form-message">${esc(state.message)}</p>`:''}<div class="admin-two-columns"><aside class="panel"><h3>Iniciativas</h3>${state.items.map(x=>`<button class="admin-list-row" data-select="${x.id}"><strong>${esc(x.titulo)}</strong><span>${esc(x.tipo)} · ${esc(x.status)}</span></button>`).join('')||'<p>Nenhuma iniciativa cadastrada.</p>'}</aside><main class="panel">${form(item)}${helps()}</main></div></section>`; bind(root); }
function value(fd,n) { return String(fd.get(n)||'').trim() || null; }
function bind(root) { root.querySelector('#new-initiative')?.addEventListener('click',()=>{state.selected=null;state.help=[];render();}); root.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',async()=>{state.selected=state.items.find(x=>x.id===b.dataset.select);state.help=await listarFormasAjuda(state.selected.id);render();})); root.querySelector('#initiative-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const titulo=value(f,'titulo');const existing=state.selected?{...state.selected}:{};await salvarIniciativa({...existing,id:state.selected?.id,tipo:value(f,'tipo'),iniciativa_pai_id:value(f,'iniciativa_pai_id'),titulo,slug:value(f,'slug')||gerarSlug(titulo),resumo:value(f,'resumo'),descricao:value(f,'descricao'),imagem_capa_url:value(f,'imagem_capa_url'),status:value(f,'status'),responsavel_nome:value(f,'responsavel_nome'),telefone:value(f,'telefone'),whatsapp:value(f,'whatsapp'),email:value(f,'email'),instagram:value(f,'instagram'),site_url:value(f,'site_url'),inicio_em:value(f,'inicio_em'),termina_em:value(f,'termina_em'),destaque:f.get('destaque')==='on',exibir_na_listagem:f.get('exibir_na_listagem')==='on'});state.message='Iniciativa salva.';await load();}); root.querySelector('#help-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await salvarFormaAjuda({iniciativa_id:state.selected.id,tipo:value(f,'tipo'),titulo:value(f,'titulo'),descricao:value(f,'descricao'),valor_publico:value(f,'valor_publico'),recebedor_nome:value(f,'recebedor_nome'),ordem:Number(f.get('ordem')||100),ativo:true});state.message='Forma de ajuda salva.';await load();}); root.querySelectorAll('[data-delete-help]').forEach(b=>b.addEventListener('click',async()=>{await excluirFormaAjuda(b.dataset.deleteHelp);state.message='Forma de ajuda removida.';await load();})); }
export async function mount() { await load(); }
