import { readFile } from "node:fs/promises";
import { createClient } from "@supabase/supabase-js";

const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, ADMIN_EMAIL, ADMIN_PASSWORD } = process.env;
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || !ADMIN_EMAIL || !ADMIN_PASSWORD) { console.error("Defina SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, ADMIN_EMAIL e ADMIN_PASSWORD neste terminal local."); process.exit(1); }
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const slugify=(value="")=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const plainText=(html="")=>html.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const readJson=async path=>{const text=await readFile(new URL(`../${path}`,import.meta.url),"utf8");try{return JSON.parse(text)}catch{return JSON.parse(text.replace(/,\s*]/g,"]"))}};
const upsert=async(table,rows)=>{if(!rows.length)return;const{error}=await supabase.from(table).upsert(rows,{onConflict:"slug"});if(error)throw new Error(`${table}: ${error.message}`);console.log(`${table}: ${rows.length} registros conferidos.`)};
const noticiasAntigas=await readJson("news-data.json"),guiaAntigo=await readJson("guia-data.json");
const noticias=noticiasAntigas.map(item=>{const resumo=plainText(item.content).slice(0,240);return{titulo:item.title,slug:slugify(item.title),resumo,conteudo_html:item.content||"",imagem_url:item.image||null,categoria_nome:"Notícias",autor:(item.author||"Equipe Eu Amo Urânia").replace(/^\s*Por\s+/i,""),status:"publicado",destaque:item.id===1,publicado_em:item.date?`${item.date}T12:00:00-03:00`:new Date().toISOString(),seo_titulo:item.title,seo_descricao:resumo.slice(0,160)}});
const guia=guiaAntigo.map(item=>({nome:item.nome,slug:slugify(item.nome),categoria_nome:item.categoria||"outros",descricao:item.descricao||"",imagem_url:item.imagem||null,whatsapp:item.whatsapp||null,instagram:item.instagram||null,endereco:item.endereco||null,recomendado:Boolean(item.destaque),status:"publicado",seo_titulo:item.nome,seo_descricao:plainText(item.descricao||"").slice(0,160)}));
const turismo=guiaAntigo.filter(item=>item.categoria==="turismo").map(item=>({nome:item.nome,slug:slugify(item.nome),descricao:item.descricao||"",conteudo_html:item.descricao?`<p>${item.descricao}</p>`:"",imagem_url:item.imagem||null,endereco:item.endereco||null,whatsapp:item.whatsapp||null,status:"publicado",destaque:Boolean(item.destaque),seo_titulo:`${item.nome} | Turismo em Urânia`,seo_descricao:plainText(item.descricao||"").slice(0,160)}));
const categorias=[{nome:"Notícias",slug:"noticias",tipo:"noticias",ordem:0,status:"ativo"},...[...new Set(guiaAntigo.map(item=>item.categoria).filter(Boolean))].map((nome,ordem)=>({nome,slug:slugify(nome),tipo:"guia",ordem,status:"ativo"})),{nome:"Pontos turísticos",slug:"pontos-turisticos",tipo:"turismo",ordem:0,status:"ativo"}];
const links=[["Nosso site","https://euamourania.com.br/","🌐"],["Canal WhatsApp","https://whatsapp.com/channel/0029VapPdlLGpLHTXQELk210","💬"],["WhatsApp","https://wa.me/5517981344558","📱"],["YouTube","https://www.youtube.com/@EuAmoUr%C3%A2nia","▶️"],["Instagram","https://instagram.com/euamourania","📷"],["Facebook","https://facebook.com/euamourania","👥"],["X (Twitter)","https://x.com/euamourania","𝕏"],["TikTok","https://tiktok.com/@euamourania","🎵"]].map(([titulo,url,icone],ordem)=>({titulo,url,icone,ordem,status:"ativo"}));
try{const{data:login,error:loginError}=await supabase.auth.signInWithPassword({email:ADMIN_EMAIL,password:ADMIN_PASSWORD});if(loginError)throw new Error(`Login: ${loginError.message}`);const{data:admin,error:adminError}=await supabase.from("usuarios_admin").select("id,ativo").eq("id",login.user.id).eq("ativo",true).maybeSingle();if(adminError)throw adminError;if(!admin)throw new Error("O usuário autenticado ainda não está ativo em usuarios_admin.");await upsert("noticias",noticias);await upsert("guia_comercial",guia);await upsert("turismo",turismo);await upsert("categorias",categorias);const{data:atuais,error:linksError}=await supabase.from("links").select("url");if(linksError)throw linksError;const urls=new Set((atuais||[]).map(item=>item.url)),novos=links.filter(item=>!urls.has(item.url));if(novos.length){const{error}=await supabase.from("links").insert(novos);if(error)throw error}console.log(`Migração concluída: ${noticias.length} notícias, ${guia.length} itens do guia, ${turismo.length} ponto turístico e ${links.length} links.`)}catch(error){console.error(error.message);process.exitCode=1}finally{await supabase.auth.signOut({scope:"local"})}
