import { fetchPublicRows, publicSupabaseConfigured } from "/assets/js/services/publicDataService.js";
import { definirMeta, textoPuro } from "/assets/js/utils.js";
import { sanitizeArticleHtml } from "/assets/js/security/sanitize-html.js";
import { responsiveImage } from "/assets/js/image-tools.js";
import { getAppDownloadConfig } from "/assets/js/services/appDownloadConfig.js";
import "/preview/guia/banners-preview.js";

const root=document.getElementById("agenda-edition-details"),params=new URLSearchParams(location.search),slug=params.get("slug")||"",year=params.get("ano")||"";
const esc=(value="")=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const strip=value=>textoPuro(value||"").replace(/\s+/g," ").trim();
const safeImage=(value,options={})=>/^https?:\/\//i.test(value||"")||/^\/?assets\//i.test(value||"")?esc(responsiveImage(value,{width:1200,height:820,quality:80,...options})):"";
const safeHttp=value=>/^https?:\/\//i.test(value||"")?esc(value):"";
const icons={share:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.6 6.8-4.2M8.6 13.4l6.8 4.2"/></svg>',map:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></svg>',calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',clock:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',pin:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>',people:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M16 5c3 0 4 2 4 4s-1 4-4 4"/></svg>'};
function dateInfo(value){if(!value)return {day:"—",month:"A definir",weekday:"",long:"Data a confirmar",time:"",iso:""};const date=new Date(value),zone="America/Sao_Paulo";if(Number.isNaN(date.getTime()))return {day:"—",month:"A definir",weekday:"",long:"Data a confirmar",time:"",iso:""};return {day:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",timeZone:zone}).format(date),month:new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:zone}).format(date).replace(".","").toUpperCase(),weekday:new Intl.DateTimeFormat("pt-BR",{weekday:"long",timeZone:zone}).format(date),long:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long",year:"numeric",timeZone:zone}).format(date),time:new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:zone}).format(date),iso:date.toISOString()};}
function statusLabel(value){return ({rascunho:"Em preparação",anunciado:"Anunciado",confirmado:"Confirmado",acontecendo:"Acontecendo",encerrado:"Encerrado",cancelado:"Cancelado"})[value]||value||"Edição";}
function parseList(raw){if(Array.isArray(raw))return raw;if(typeof raw==="string"){try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[];}catch{return raw.split(/[\n,]/).map(value=>value.trim()).filter(Boolean);}}return [];}
function fact(icon,label,value,extra=""){return value?`<div class="event-fact">${icon}<div><small>${esc(label)}</small><strong>${esc(value)}</strong>${extra}</div></div>`:"";}
function contentSection(kicker,title,html,className=""){return html?`<section class="edition-content-section ${className}"><header><p class="event-kicker">${esc(kicker)}</p><h2>${esc(title)}</h2></header><div class="edition-rich-copy">${sanitizeArticleHtml(html)}</div></section>`:"";}
function galleryMarkup(item,title="Galeria da edição"){const images=parseList(item.galeria).map(value=>safeImage(typeof value==="string"?value:value?.url||value?.imagem_url,{width:760,height:560,quality:76})).filter(Boolean).slice(0,8);if(!images.length)return "";return `<section class="edition-gallery"><header><p class="event-kicker">Registros</p><h2>${esc(title)}.</h2></header><div>${images.map((image,index)=>`<button type="button" aria-label="Ampliar foto ${index+1}"><img src="${image}" alt="Registro ${index+1} desta edição" width="760" height="560" loading="lazy" decoding="async"></button>`).join("")}</div></section>`;}
function sponsorsMarkup(raw){const items=parseList(raw);if(!items.length)return "";return `<section class="edition-sponsors"><header><p class="event-kicker">Apoio</p><h2>Patrocinadores e parceiros.</h2></header><div>${items.map(item=>{const name=typeof item==="string"?item:item.nome||item.titulo||"Parceiro",logo=safeImage(typeof item==="object"?(item.logo||item.imagem||item.url):"");return `<article>${logo?`<img src="${logo}" alt="${esc(name)}" width="160" height="90" loading="lazy">`:""}<strong>${esc(name)}</strong></article>`;}).join("")}</div></section>`;}
async function render(){
  if(!publicSupabaseConfigured()||!slug||!year){root.innerHTML='<p class="event-detail-status">Edição não encontrada.</p>';return;}
  try{
    const [event]=await fetchPublicRows("eventos_principais",{select:"*",slug:`eq.${slug}`,ativo:"eq.true",limit:"1"});if(!event)throw new Error("event-not-found");
    const [edition]=await fetchPublicRows("eventos_edicoes",{select:"*",evento_id:`eq.${event.id}`,ano:`eq.${year}`,limit:"1"});if(!edition)throw new Error("edition-not-found");
    const start=dateInfo(edition.data_inicio),end=dateInfo(edition.data_fim),image=safeImage(edition.banner_url||edition.cartaz_url||event.imagem_capa_url),map=safeHttp(edition.mapa_url)||((edition.local||event.local_tradicional)?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([edition.local||event.local_tradicional,"Urânia SP"].join(" "))}`:""),summary=strip(edition.subtitulo||event.descricao_curta||edition.programacao_html)||`Confira as informações da edição ${edition.ano} de ${event.nome}.`,canonical=`https://euamourania.com.br/eventos/${encodeURIComponent(event.slug)}/${encodeURIComponent(edition.ano)}`;
    const programHtml=edition.programacao_html?sanitizeArticleHtml(edition.programacao_html):`<p>${esc(summary)}</p>`,programCollapsed=strip(edition.programacao_html||summary).length>560;
    definirMeta({titulo:edition.seo_titulo||`${edition.titulo||`${event.nome} ${edition.ano}`} | Eu Amo Urânia`,descricao:(edition.seo_descricao||summary).slice(0,160),imagem:image||"/assets/compartilhamento-logo.png",url:canonical});
    const structured=document.createElement("script");structured.type="application/ld+json";structured.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Event",name:edition.titulo||`${event.nome} ${edition.ano}`,description:summary,url:canonical,image:image?new URL(image,location.origin).href:undefined,startDate:edition.data_inicio||undefined,endDate:edition.data_fim||undefined,eventStatus:edition.status==="cancelado"?"https://schema.org/EventCancelled":"https://schema.org/EventScheduled",eventAttendanceMode:"https://schema.org/OfflineEventAttendanceMode",location:edition.local||event.local_tradicional?{"@type":"Place",name:edition.local||event.local_tradicional}:undefined});document.head.appendChild(structured);
    root.innerHTML=`<article class="edition-detail"><nav class="event-breadcrumb" aria-label="Navegação estrutural"><a href="/preview/agenda/">Agenda</a><span>/</span><a href="/preview/agenda/tradicao/?slug=${encodeURIComponent(event.slug)}">${esc(event.nome)}</a><span>/</span><span aria-current="page">${esc(edition.ano)}</span></nav><section class="event-detail-hero edition-hero${image?" has-image":" no-image"}">${image?`<div class="event-detail-media"><img src="${image}" alt="${esc(edition.titulo||event.nome)}" width="1200" height="820" fetchpriority="high" decoding="async"></div>`:"<div class=\"event-detail-media event-detail-placeholder\"><span>Edição do evento</span></div>"}<time class="event-date-signature" datetime="${esc(start.iso)}"><strong>${esc(start.day)}</strong><span>${esc(start.month)}</span><small>${esc(start.weekday)}</small></time><header class="event-detail-intro"><div class="event-detail-labels"><span>${esc(event.nome)}</span><b>${esc(statusLabel(edition.status))}</b></div><h1>${esc(edition.titulo||`${event.nome} ${edition.ano}`)}</h1><p>${esc(summary)}</p><div class="event-detail-actions">${map?`<a class="event-action primary" href="${map}" target="_blank" rel="noopener">${icons.map}<span>Abrir mapa</span></a>`:""}<button class="event-icon-action" type="button" data-share-event aria-label="Compartilhar edição">${icons.share}</button></div></header></section>
      <section class="edition-overview"><div><p class="event-kicker">Edição ${esc(edition.ano)}</p><h2>Informações da programação.</h2><div id="edition-program" class="edition-rich-copy edition-program${programCollapsed?" is-collapsed":""}">${programHtml}</div>${programCollapsed?'<button class="edition-read-more" type="button" aria-expanded="false" aria-controls="edition-program"><span>Ver mais</span><b aria-hidden="true">↓</b></button>':""}</div><aside class="event-info-panel"><p class="event-kicker">Quando e onde</p><h2>Planeje-se.</h2>${fact(icons.calendar,"Início",start.long,start.time?`<span>${esc(start.time)}</span>`:"")}${fact(icons.clock,"Término",edition.data_fim?end.long:"",edition.data_fim&&end.time?`<span>${esc(end.time)}</span>`:"")}${fact(icons.pin,"Local",edition.local||event.local_tradicional)}${fact(icons.people,"Público estimado",edition.publico_estimado?Number(edition.publico_estimado).toLocaleString("pt-BR"):"")}${map?`<a class="event-panel-map" href="${map}" target="_blank" rel="noopener">${icons.map}<span>Abrir no mapa</span><b aria-hidden="true">→</b></a>`:""}</aside></section>
      ${contentSection("Atrações","Destaques confirmados.",edition.atracoes_html,"edition-attractions")}${edition.cartaz_url?`<section class="edition-poster"><div><p class="event-kicker">Cartaz oficial</p><h2>Divulgação da edição.</h2><p>Confira o material oficial publicado pela organização.</p></div><img src="${safeImage(edition.cartaz_url,{width:900,height:1270,quality:80})}" alt="Cartaz oficial de ${esc(edition.titulo||event.nome)}" width="900" height="1270" loading="lazy" decoding="async"></section>`:""}${galleryMarkup(edition)}${sponsorsMarkup(edition.patrocinadores)}${contentSection("Após o evento","Resumo da edição.",edition.resumo_pos_evento_html,"edition-summary")}</article>`;
    root.querySelector("[data-share-event]")?.addEventListener("click",async eventButton=>{try{if(navigator.share){await navigator.share({title:edition.titulo||event.nome,text:summary,url:canonical});return;}await navigator.clipboard.writeText(canonical);eventButton.currentTarget.classList.add("copied");}catch(error){if(error?.name!=="AbortError")location.href=`https://wa.me/?text=${encodeURIComponent(`${edition.titulo||event.nome}: ${canonical}`)}`;}});
    root.querySelector(".edition-read-more")?.addEventListener("click",eventButton=>{const button=eventButton.currentTarget,content=root.querySelector("#edition-program"),expanded=button.getAttribute("aria-expanded")==="true";button.setAttribute("aria-expanded",String(!expanded));content?.classList.toggle("is-collapsed",expanded);button.querySelector("span").textContent=expanded?"Ver mais":"Ver menos";});
  }catch(error){console.error(error);root.innerHTML='<p class="event-detail-status">Não foi possível carregar esta edição.</p>';}
}
const header=document.querySelector(".site-header"),menu=document.getElementById("menu-principal"),menuButton=header?.querySelector(".menu-toggle"),searchTrigger=header?.querySelector(".search-trigger"),searchInput=document.getElementById("header-search-input");const closeSearch=()=>{header?.classList.remove("search-open");searchTrigger?.setAttribute("aria-expanded","false");};searchTrigger?.addEventListener("click",()=>{menu?.classList.remove("is-open");menuButton?.setAttribute("aria-expanded","false");header?.classList.add("search-open");searchTrigger.setAttribute("aria-expanded","true");setTimeout(()=>searchInput?.focus(),180);});menuButton?.addEventListener("click",()=>{closeSearch();const open=menuButton.getAttribute("aria-expanded")!=="true";menuButton.setAttribute("aria-expanded",String(open));menu?.classList.toggle("is-open",open);});header?.querySelector(".header-search-close")?.addEventListener("click",closeSearch);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeSearch();});document.getElementById("year").textContent=new Date().getFullYear();getAppDownloadConfig().then(app=>document.querySelectorAll("[data-app-download]").forEach(link=>{link.href=app.googlePlayUrl||app.appStoreUrl||app.appPageUrl||"/app.html";})).catch(()=>{});
function configureNewsletter(){const signup=document.querySelector(".newsletter-signup");if(!signup)return false;const title=signup.querySelector("h2"),description=signup.querySelector(".newsletter-box > div > p:last-child"),name=signup.querySelector('input[name="nome"]');if(title)title.textContent="Urânia direto no seu e-mail.";if(description)description.textContent="Receba notícias importantes, novidades da cidade e conteúdos do Eu Amo Urânia.";if(name){name.placeholder="Seu nome";name.required=true;}return true;}
render().then(()=>Promise.allSettled([import("/assets/js/pages/site-config-page.js"),import("/assets/js/pages/analytics-page.js"),import("/assets/js/pages/newsletter-public.js"),import("/assets/js/pages/google-analytics-page.js"),import("/assets/js/pages/smart-app-banner.js"),import("/assets/js/pages/error-monitor.js")])).then(()=>{if(configureNewsletter())return;const observer=new MutationObserver(()=>{if(configureNewsletter())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),10000);});
