-- Eu Amo Urânia — CMS profissional v2
-- Execute no SQL Editor antes de publicar esta branch.

alter table public.categorias drop constraint if exists categorias_tipo_check;
alter table public.categorias add constraint categorias_tipo_check
check (tipo in ('noticias','guia','turismo','eventos','publicidade'));

alter table public.campanhas_publicitarias
add column if not exists categoria_id uuid references public.categorias(id) on delete set null;

create table if not exists public.analytics_eventos (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('page_view','noticia_view','guia_view','whatsapp_click','external_click')),
  pagina text not null,
  recurso_tipo text,
  recurso_id uuid,
  destino text,
  criado_em timestamptz not null default now(),
  dia date generated always as ((criado_em at time zone 'America/Sao_Paulo')::date) stored
);
create index if not exists analytics_eventos_dia_idx on public.analytics_eventos(dia desc,tipo);
create index if not exists analytics_eventos_recurso_idx on public.analytics_eventos(recurso_tipo,recurso_id);
alter table public.analytics_eventos enable row level security;
drop policy if exists "admin_consulta_analytics" on public.analytics_eventos;
create policy "admin_consulta_analytics" on public.analytics_eventos for select to authenticated using(public.is_admin());

create or replace function public.registrar_evento_site(
 p_tipo text,p_pagina text,p_recurso_tipo text default null,p_recurso_id uuid default null,p_destino text default null
) returns void language plpgsql security definer set search_path=public as $$
begin
 if p_tipo not in('page_view','noticia_view','guia_view','whatsapp_click','external_click') then return; end if;
 insert into public.analytics_eventos(tipo,pagina,recurso_tipo,recurso_id,destino)
 values(p_tipo,left(coalesce(p_pagina,'/'),300),left(p_recurso_tipo,40),p_recurso_id,left(p_destino,500));
 if p_tipo='noticia_view' and p_recurso_id is not null then
   update public.noticias set visualizacoes=visualizacoes+1 where id=p_recurso_id and status='publicado';
 elsif p_tipo='guia_view' and p_recurso_id is not null then
   update public.guia_comercial set visualizacoes=visualizacoes+1 where id=p_recurso_id and status='publicado';
 end if;
end $$;
revoke all on function public.registrar_evento_site(text,text,text,uuid,text) from public;
grant execute on function public.registrar_evento_site(text,text,text,uuid,text) to anon,authenticated;

create or replace function public.contagem_categoria(p_categoria uuid,p_tipo text)
returns bigint language plpgsql stable security definer set search_path=public as $$
declare n bigint:=0;
begin
 case p_tipo
  when 'noticias' then select count(*) into n from noticias where categoria_id=p_categoria;
  when 'guia' then select count(*) into n from guia_comercial where categoria_id=p_categoria;
  when 'turismo' then select count(*) into n from turismo where categoria_id=p_categoria;
  when 'eventos' then select count(*) into n from eventos where categoria_id=p_categoria;
  when 'publicidade' then select count(*) into n from campanhas_publicitarias where categoria_id=p_categoria;
  else n:=0;
 end case;
 return n;
end $$;
grant execute on function public.contagem_categoria(uuid,text) to authenticated;

create or replace function public.impedir_exclusao_categoria_usada()
returns trigger language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
 n:=public.contagem_categoria(old.id,old.tipo);
 if n>0 then raise exception 'Esta categoria está em uso por % item(ns). Mova os itens antes de excluir.',n using errcode='23503'; end if;
 return old;
end $$;
drop trigger if exists categorias_impedir_exclusao on public.categorias;
create trigger categorias_impedir_exclusao before delete on public.categorias
for each row execute function public.impedir_exclusao_categoria_usada();

insert into public.configuracoes_site(chave,valor,tipo) values
 ('descricao_site','Informação, turismo e comunidade.','textarea'),
 ('whatsapp','5517981344558','telefone'),
 ('instagram','','url'),('facebook','','url'),('youtube','','url'),
 ('imagem_compartilhamento','https://euamourania.com.br/assets/AD3A1763-min%20(1).jpg','url'),
 ('logo_site','/assets/1505 - Urania - Logo Horizontal - 1.png','url'),
 ('texto_rodape','Informação, turismo e comunidade.','textarea'),
 ('link_quem_somos','/quem-somos.html','url'),
 ('link_privacidade','/politica-de-privacidade.html','url'),
 ('link_termos','/termos-de-servico.html','url')
on conflict(chave) do nothing;

create or replace view public.categorias_com_contagem with(security_invoker=true) as
select c.*,public.contagem_categoria(c.id,c.tipo) as total_itens from public.categorias c;
grant select on public.categorias_com_contagem to authenticated;
