-- Conteúdo global administrável. Valores existentes nunca são sobrescritos.
insert into public.configuracoes_site(chave,valor,tipo) values
('nome_site','Eu Amo Urânia','texto'),('slogan','Informação, turismo e comunidade.','texto'),
('descricao_site','O Eu Amo Urânia conecta moradores, visitantes e negócios por meio de informação local, boas histórias e lugares que merecem ser descobertos.','textarea'),
('email_contato','euamourania@gmail.com','email'),('whatsapp','5517981344558','telefone'),
('whatsapp_canal','https://whatsapp.com/channel/0029VapPdlLGpLHTXQELk210','url'),
('instagram','','url'),('facebook','','url'),('youtube','','url'),('tiktok','','url'),
('endereco','','texto'),('horario_atendimento','','texto'),
('logo_principal','/assets/1505 - Urania - Logo Horizontal - 1.png','url'),('logo_negativa','/assets/1505 - Urania - Logo Horizontal - 1.png','url'),
('favicon','/assets/Design sem nome (9).png','url'),('imagem_compartilhamento','/assets/compartilhamento-logo.png','url'),
('imagem_padrao_noticia','','url'),('imagem_padrao_guia','','url'),
('imagem_padrao_turismo','/assets/AD3A1763-min (1).jpg','url'),('imagem_padrao_evento','','url'),
('home_hero_imagem','/assets/AD3A1763-min (1).jpg','url'),('home_hero_alt','Entrada do Borboletário Municipal de Urânia cercada por natureza','texto'),
('home_hero_eyebrow','Feito em Urânia, para Urânia','texto'),('home_hero_titulo','A nossa cidade.','texto'),('home_hero_destaque','Mais perto de você.','texto'),
('home_hero_texto','O Eu Amo Urânia conecta moradores, visitantes e negócios por meio de informação local, boas histórias e lugares que merecem ser descobertos.','textarea'),
('home_botao_1_texto','Explorar o guia da cidade','texto'),('home_botao_1_link','/guia.html','url'),('home_botao_2_texto','Ver as últimas notícias','texto'),('home_botao_2_link','/news/','url'),
('home_topicos','["Notícias locais","Turismo","Comércio e serviços"]','json'),
('home_atalhos_eyebrow','Encontre o que precisa','texto'),('home_atalhos_titulo','Urânia em um só lugar','texto'),('home_atalhos_texto','Informação útil, direta e feita para o dia a dia da nossa comunidade.','textarea'),
('home_cards','[{"titulo":"Notícias","texto":"Acompanhe acontecimentos, eventos e novidades da cidade.","botao":"Ler notícias","link":"/news/"},{"titulo":"Guia da cidade","texto":"Descubra onde comer, comprar, visitar e encontrar serviços.","botao":"Abrir o guia","link":"/guia.html"},{"titulo":"Nossos canais","texto":"Encontre o Eu Amo Urânia nas redes e fique sempre por perto.","botao":"Ver todos os links","link":"/links/"}]','json'),
('home_turismo_imagem_1','/assets/3Q2A7854-min-min.jpg','url'),('home_turismo_imagem_2','/assets/1V4A4044-min.jpg','url'),
('home_turismo_eyebrow','Vale a visita','texto'),('home_turismo_titulo','Conheça o Borboletário Municipal','texto'),
('home_turismo_texto','O primeiro borboletário da Região Noroeste Paulista é um convite para aprender, contemplar a natureza e viver uma experiência diferente bem aqui em Urânia.','textarea'),
('home_turismo_nota','Inaugurado em 2022, o espaço recebe visitantes mediante agendamento.','textarea'),
('home_turismo_botao_texto','Agendar uma visita','texto'),('home_turismo_botao_link','https://borboletario-municipal-de-urania.reservio.com/','url'),
('home_essencia_eyebrow','Nossa essência','texto'),('home_essencia_titulo','Amar Urânia também é compartilhar o que ela tem de melhor.','texto'),
('home_essencia_texto_1','O Eu Amo Urânia nasceu para valorizar a cidade, dar visibilidade a quem faz parte dela e facilitar o acesso a informações que realmente importam.','textarea'),
('home_essencia_texto_2','Somos um ponto de encontro digital para histórias, serviços, turismo, cultura e tudo o que fortalece o sentimento de comunidade.','textarea'),
('home_whatsapp_eyebrow','Faça parte','texto'),('home_whatsapp_titulo','Receba Urânia no seu WhatsApp','texto'),('home_whatsapp_texto','Notícias, eventos e novidades da cidade em um canal direto e fácil de acompanhar.','textarea'),('home_whatsapp_botao','Entrar no canal','texto'),
('newsletter_titulo','Receba as novidades de Urânia no seu e-mail','texto'),('newsletter_texto','Notícias, eventos e informações importantes direto na sua caixa de entrada.','textarea'),
('quem_eyebrow','Nossa história','texto'),('quem_titulo','Feito por quem acredita em Urânia','texto'),('quem_subtitulo','Um projeto independente para informar, conectar e valorizar tudo o que torna nossa cidade especial.','textarea'),
('quem_bloco_titulo','A cidade ganha força quando suas histórias são compartilhadas.','texto'),
('quem_texto_1','Nascemos com o propósito de aproximar moradores, visitantes, negócios e iniciativas locais. Reunimos notícias, serviços, turismo e histórias em um espaço simples e útil para a comunidade.','textarea'),
('quem_texto_2','Mais do que divulgar acontecimentos, queremos fortalecer o sentimento de pertencimento, valorizar quem trabalha pela cidade e ajudar mais pessoas a descobrir Urânia.','textarea'),
('quem_botao_texto','Conhecer o guia da cidade','texto'),('quem_botao_link','/guia.html','url'),
('quem_valores','[{"rotulo":"01 · INFORMAR","titulo":"Conteúdo local","texto":"Informação clara sobre os fatos e acontecimentos que impactam a comunidade."},{"rotulo":"02 · VALORIZAR","titulo":"Orgulho da cidade","texto":"Espaço para lugares, pessoas e iniciativas que fazem Urânia avançar."},{"rotulo":"03 · CONECTAR","titulo":"Comunidade próxima","texto":"Canais que facilitam o encontro entre moradores, visitantes e negócios."}]','json'),
('quem_cta_eyebrow','Fale com a gente','texto'),('quem_cta_titulo','Tem uma história de Urânia para contar?','texto'),('quem_cta_texto','Envie uma sugestão, notícia ou iniciativa que merece ganhar visibilidade.','textarea'),('quem_cta_botao','Entrar em contato','texto'),
('termos_html','','html'),('privacidade_html','','html'),('texto_rodape','Informação, turismo e comunidade.','textarea'),('copyright','Eu Amo Urânia. Todos os direitos reservados.','texto'),
('menu_itens','[{"titulo":"Início","url":"/","ativo":true,"nova_aba":false},{"titulo":"Guia da cidade","url":"/guia.html","ativo":true,"nova_aba":false},{"titulo":"Turismo","url":"/turismo.html","ativo":true,"nova_aba":false},{"titulo":"Notícias","url":"/news/","ativo":true,"nova_aba":false},{"titulo":"Quem somos","url":"/quem-somos.html","ativo":true,"nova_aba":false}]','json'),
('rodape_links','[{"titulo":"Turismo","url":"/turismo.html","ativo":true},{"titulo":"Contato","url":"mailto:euamourania@gmail.com","ativo":true},{"titulo":"Termos de serviço","url":"/termos-de-servico.html","ativo":true},{"titulo":"Privacidade","url":"/politica-de-privacidade.html","ativo":true}]','json'),
('seo_titulo_padrao','Eu Amo Urânia | Guia, notícias e turismo','texto'),('seo_descricao_padrao','Informação local, turismo, guia da cidade, eventos e histórias de Urânia.','textarea'),('seo_palavras_chave','Urânia, notícias de Urânia, turismo em Urânia, guia comercial','texto'),('seo_autor','Eu Amo Urânia','texto'),('seo_publicador','Eu Amo Urânia','texto'),('seo_logo','/assets/Design sem nome (9).png','url'),('dominio_principal','https://euamourania.com.br','url')
on conflict(chave) do nothing;
