-- Eu Amo Urânia — Comunicação/Newsletter
create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists public.newsletter_assinantes(
 id uuid primary key default gen_random_uuid(), nome text, email citext unique not null,
 cidade text, origem text not null default 'site', interesses text[] not null default array['tudo']::text[],
 status text not null default 'ativo' check(status in('ativo','inativo','descadastrado')),
 token_descadastro uuid unique not null default gen_random_uuid(), cadastrado_em timestamptz not null default now(),
 atualizado_em timestamptz not null default now(), descadastrado_em timestamptz,
 constraint newsletter_interesses_validos check(interesses <@ array['noticias','eventos','turismo','comercio','promocoes','esportes','politica','tudo']::text[])
);
create table if not exists public.newsletters(
 id uuid primary key default gen_random_uuid(), titulo text not null, assunto text not null,
 preheader text, imagem_url text, conteudo_html text not null default '', texto_botao text,
 link_botao text, interesses_alvo text[] not null default array['tudo']::text[],
 status text not null default 'rascunho' check(status in('rascunho','agendado','enviando','enviado','erro')),
 agendado_em timestamptz, enviado_em timestamptz, total_enviados integer not null default 0,
 total_entregues integer not null default 0, total_aberturas integer not null default 0,
 total_cliques integer not null default 0, total_descadastros integer not null default 0,
 automatizacao_tipo text, configuracao_futura jsonb not null default '{}'::jsonb,
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.newsletter_envios(
 id bigint generated by default as identity primary key,
 newsletter_id uuid not null references public.newsletters(id) on delete cascade,
 assinante_id uuid references public.newsletter_assinantes(id) on delete set null,
 brevo_message_id text, status text not null default 'enviado', aberturas integer not null default 0,
 cliques integer not null default 0, aberto_em timestamptz, clicado_em timestamptz,
 enviado_em timestamptz not null default now(), unique(newsletter_id,assinante_id)
);
create index if not exists newsletter_assinantes_status_idx on public.newsletter_assinantes(status,cadastrado_em desc);
create index if not exists newsletters_status_idx on public.newsletters(status,criado_em desc);
create index if not exists newsletter_envios_campanha_idx on public.newsletter_envios(newsletter_id,status);

create or replace trigger newsletter_assinantes_atualizado before update on public.newsletter_assinantes for each row execute function public.set_atualizado_em();
create or replace trigger newsletters_atualizado before update on public.newsletters for each row execute function public.set_atualizado_em();

alter table public.newsletter_assinantes enable row level security;
alter table public.newsletters enable row level security;
alter table public.newsletter_envios enable row level security;
create policy "admin_gerencia_assinantes" on public.newsletter_assinantes for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin_gerencia_newsletters" on public.newsletters for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin_consulta_envios" on public.newsletter_envios for all to authenticated using(public.is_admin()) with check(public.is_admin());

create or replace function public.assinar_newsletter(p_email text,p_nome text default null,p_cidade text default null,p_origem text default 'site',p_interesses text[] default array['tudo'])
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_email citext;v_interesses text[];
begin
 v_email=lower(trim(p_email));if v_email!~*'^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then raise exception 'E-mail inválido';end if;
 select array_agg(distinct x) into v_interesses from unnest(coalesce(p_interesses,array['tudo']))x where x=any(array['noticias','eventos','turismo','comercio','promocoes','esportes','politica','tudo']);
 if v_interesses is null then v_interesses=array['tudo'];end if;
 insert into newsletter_assinantes(email,nome,cidade,origem,interesses,status,descadastrado_em)
 values(v_email,nullif(trim(p_nome),''),nullif(trim(p_cidade),''),coalesce(nullif(trim(p_origem),''),'site'),v_interesses,'ativo',null)
 on conflict(email)do update set nome=coalesce(excluded.nome,newsletter_assinantes.nome),cidade=coalesce(excluded.cidade,newsletter_assinantes.cidade),interesses=excluded.interesses,status='ativo',descadastrado_em=null;
 return jsonb_build_object('ok',true,'mensagem','Cadastro realizado com sucesso.');
end $$;
revoke all on function public.assinar_newsletter(text,text,text,text,text[]) from public;
grant execute on function public.assinar_newsletter(text,text,text,text,text[]) to anon,authenticated;

create or replace function public.descadastrar_newsletter(p_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare n integer;
begin update newsletter_assinantes set status='descadastrado',descadastrado_em=now() where token_descadastro=p_token and status<>'descadastrado';get diagnostics n=row_count;return jsonb_build_object('ok',true,'alterado',n>0);end $$;
revoke all on function public.descadastrar_newsletter(uuid) from public;
grant execute on function public.descadastrar_newsletter(uuid) to anon,authenticated;

create or replace function public.registrar_evento_newsletter(p_newsletter uuid,p_token uuid,p_tipo text)
returns void language plpgsql security definer set search_path=public as $$
declare aid uuid;
begin select id into aid from newsletter_assinantes where token_descadastro=p_token;if aid is null or p_tipo not in('abertura','clique')then return;end if;
 insert into newsletter_envios(newsletter_id,assinante_id,status,aberturas,cliques,aberto_em,clicado_em)
 values(p_newsletter,aid,'enviado',case when p_tipo='abertura'then 1 else 0 end,case when p_tipo='clique'then 1 else 0 end,case when p_tipo='abertura'then now()end,case when p_tipo='clique'then now()end)
 on conflict(newsletter_id,assinante_id)do update set aberturas=newsletter_envios.aberturas+case when p_tipo='abertura'then 1 else 0 end,cliques=newsletter_envios.cliques+case when p_tipo='clique'then 1 else 0 end,aberto_em=case when p_tipo='abertura'then coalesce(newsletter_envios.aberto_em,now())else newsletter_envios.aberto_em end,clicado_em=case when p_tipo='clique'then now()else newsletter_envios.clicado_em end;
 update newsletters set total_aberturas=(select count(*) from newsletter_envios where newsletter_id=p_newsletter and aberturas>0),total_cliques=(select sum(cliques) from newsletter_envios where newsletter_id=p_newsletter)where id=p_newsletter;
end $$;
revoke all on function public.registrar_evento_newsletter(uuid,uuid,text) from public;
grant execute on function public.registrar_evento_newsletter(uuid,uuid,text) to anon,authenticated;

create or replace view public.comunicacao_resumo with(security_invoker=true)as
select (select count(*) from newsletter_assinantes)total_assinantes,(select count(*) from newsletter_assinantes where status='ativo')assinantes_ativos,(select count(*) from newsletter_assinantes where status='descadastrado')descadastros,(select count(*) from newsletters where status='enviado')campanhas_enviadas,coalesce((select sum(total_aberturas)from newsletters),0)aberturas,coalesce((select sum(total_cliques)from newsletters),0)cliques,case when coalesce((select sum(total_enviados)from newsletters),0)=0 then 0 else round(coalesce((select sum(total_cliques)from newsletters),0)::numeric*100/(select sum(total_enviados)from newsletters),2)end taxa_cliques;
grant select on public.comunicacao_resumo to authenticated;
