-- Eu Amo Urânia — módulo profissional de Publicidade
-- Execute este arquivo no SQL Editor do Supabase antes de publicar o front-end.

create extension if not exists pgcrypto;

create table if not exists public.anunciantes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  logo_url text,
  contato_email text,
  whatsapp text,
  status text not null default 'ativo' check (status in ('ativo','inativo')),
  usuario_id uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.campanhas_publicitarias (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  anunciante_id uuid references public.anunciantes(id) on delete set null,
  empresa_anunciante text not null,
  logo_empresa_url text,
  tipo text not null default 'banner' check (tipo in ('banner','popup','video')),
  imagem_url text,
  video_url text,
  link_destino text,
  texto_botao text,
  abrir_nova_aba boolean not null default true,
  prioridade integer not null default 0,
  status text not null default 'rascunho' check (status in ('rascunho','ativo','pausado','encerrado')),
  data_inicio timestamptz,
  data_fim timestamptz,
  popup_uma_vez boolean not null default true,
  popup_reexibir text not null default '24h' check (popup_reexibir in ('24h','7d','sempre')),
  popup_atraso_seg integer not null default 3 check (popup_atraso_seg between 0 and 300),
  popup_botao_fechar boolean not null default true,
  configuracao_futura jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint campanha_periodo_valido check (data_fim is null or data_inicio is null or data_fim >= data_inicio),
  constraint campanha_midia check (imagem_url is not null or video_url is not null or status = 'rascunho')
);

create table if not exists public.campanha_posicoes (
  campanha_id uuid not null references public.campanhas_publicitarias(id) on delete cascade,
  posicao text not null check (posicao in (
    'home_topo','home_hero_conteudo','home_entre_secoes','home_rodape',
    'noticias_topo','noticias_entre_listagem','noticia_meio','noticia_final',
    'guia_topo','guia_entre_estabelecimentos','guia_rodape',
    'turismo_topo','turismo_entre_cartoes','turismo_rodape',
    'eventos_topo','eventos_entre_eventos','eventos_rodape','todas_paginas'
  )),
  criado_em timestamptz not null default now(),
  primary key (campanha_id, posicao)
);

create table if not exists public.publicidade_metricas_diarias (
  id bigint generated by default as identity primary key,
  campanha_id uuid not null references public.campanhas_publicitarias(id) on delete cascade,
  dia date not null default current_date,
  impressoes bigint not null default 0 check (impressoes >= 0),
  cliques bigint not null default 0 check (cliques >= 0),
  ultima_visualizacao timestamptz,
  ultimo_clique timestamptz,
  unique (campanha_id, dia)
);

create table if not exists public.cms_atividades (
  id bigint generated by default as identity primary key,
  tabela text not null,
  registro_id text,
  acao text not null check (acao in ('criado','atualizado','excluido')),
  titulo text,
  usuario_id uuid references auth.users(id) on delete set null,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists campanhas_publicitarias_status_periodo_idx on public.campanhas_publicitarias (status, data_inicio, data_fim);
create index if not exists campanhas_publicitarias_prioridade_idx on public.campanhas_publicitarias (prioridade desc);
create index if not exists campanha_posicoes_posicao_idx on public.campanha_posicoes (posicao);
create index if not exists publicidade_metricas_campanha_dia_idx on public.publicidade_metricas_diarias (campanha_id, dia desc);
create index if not exists cms_atividades_criado_idx on public.cms_atividades (criado_em desc);

create or replace function public.definir_atualizado_em()
returns trigger language plpgsql as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists anunciantes_atualizado_em on public.anunciantes;
create trigger anunciantes_atualizado_em before update on public.anunciantes
for each row execute function public.definir_atualizado_em();

drop trigger if exists campanhas_atualizado_em on public.campanhas_publicitarias;
create trigger campanhas_atualizado_em before update on public.campanhas_publicitarias
for each row execute function public.definir_atualizado_em();

alter table public.anunciantes enable row level security;
alter table public.campanhas_publicitarias enable row level security;
alter table public.campanha_posicoes enable row level security;
alter table public.publicidade_metricas_diarias enable row level security;
alter table public.cms_atividades enable row level security;

drop policy if exists "Publicidade ativa visivel" on public.campanhas_publicitarias;
create policy "Publicidade ativa visivel" on public.campanhas_publicitarias for select
using (
  status = 'ativo'
  and (data_inicio is null or data_inicio <= now())
  and (data_fim is null or data_fim >= now())
  or public.is_admin()
);

drop policy if exists "Administradores gerenciam publicidade" on public.campanhas_publicitarias;
create policy "Administradores gerenciam publicidade" on public.campanhas_publicitarias for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Posicoes publicas de campanhas" on public.campanha_posicoes;
create policy "Posicoes publicas de campanhas" on public.campanha_posicoes for select
using (exists (
  select 1 from public.campanhas_publicitarias c
  where c.id = campanha_id
));

drop policy if exists "Administradores gerenciam posicoes" on public.campanha_posicoes;
create policy "Administradores gerenciam posicoes" on public.campanha_posicoes for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Administradores gerenciam anunciantes" on public.anunciantes;
create policy "Administradores gerenciam anunciantes" on public.anunciantes for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Administradores consultam metricas" on public.publicidade_metricas_diarias;
create policy "Administradores consultam metricas" on public.publicidade_metricas_diarias for select
using (public.is_admin());

drop policy if exists "Administradores consultam atividades" on public.cms_atividades;
create policy "Administradores consultam atividades" on public.cms_atividades for select
using (public.is_admin());

create or replace function public.registrar_evento_publicidade(
  p_campanha uuid,
  p_tipo text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_tipo not in ('impressao','clique') then
    raise exception 'Tipo de evento inválido';
  end if;

  if not exists (
    select 1 from public.campanhas_publicitarias
    where id = p_campanha and status = 'ativo'
      and (data_inicio is null or data_inicio <= now())
      and (data_fim is null or data_fim >= now())
  ) then
    return;
  end if;

  insert into public.publicidade_metricas_diarias (
    campanha_id, dia, impressoes, cliques, ultima_visualizacao, ultimo_clique
  ) values (
    p_campanha, current_date,
    case when p_tipo = 'impressao' then 1 else 0 end,
    case when p_tipo = 'clique' then 1 else 0 end,
    case when p_tipo = 'impressao' then now() else null end,
    case when p_tipo = 'clique' then now() else null end
  )
  on conflict (campanha_id, dia) do update set
    impressoes = publicidade_metricas_diarias.impressoes + case when p_tipo = 'impressao' then 1 else 0 end,
    cliques = publicidade_metricas_diarias.cliques + case when p_tipo = 'clique' then 1 else 0 end,
    ultima_visualizacao = case when p_tipo = 'impressao' then now() else publicidade_metricas_diarias.ultima_visualizacao end,
    ultimo_clique = case when p_tipo = 'clique' then now() else publicidade_metricas_diarias.ultimo_clique end;
end;
$$;

revoke all on function public.registrar_evento_publicidade(uuid,text) from public;
grant execute on function public.registrar_evento_publicidade(uuid,text) to anon, authenticated;

create or replace function public.registrar_atividade_cms()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_registro jsonb;
  v_acao text;
  v_id text;
  v_titulo text;
begin
  if tg_op = 'DELETE' then
    v_registro := to_jsonb(old);
    v_acao := 'excluido';
  elsif tg_op = 'INSERT' then
    v_registro := to_jsonb(new);
    v_acao := 'criado';
  else
    v_registro := to_jsonb(new);
    v_acao := 'atualizado';
  end if;
  v_id := coalesce(v_registro->>'id','');
  v_titulo := coalesce(v_registro->>'titulo', v_registro->>'nome', v_registro->>'chave', v_id);
  insert into public.cms_atividades (tabela, registro_id, acao, titulo, usuario_id)
  values (tg_table_name, v_id, v_acao, v_titulo, auth.uid());
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array['noticias','guia_comercial','turismo','eventos','links','campanhas_publicitarias']
  loop
    if to_regclass('public.' || t) is not null then
      execute format('drop trigger if exists cms_atividade_%I on public.%I', t, t);
      execute format('create trigger cms_atividade_%I after insert or update or delete on public.%I for each row execute function public.registrar_atividade_cms()', t, t);
    end if;
  end loop;
end $$;

create or replace view public.publicidade_resumo
with (security_invoker = true)
as
select
  c.id, c.nome, c.empresa_anunciante, c.tipo, c.status, c.prioridade,
  c.data_inicio, c.data_fim, c.criado_em, c.atualizado_em,
  case
    when c.status = 'encerrado' or (c.data_fim is not null and c.data_fim < now()) then 'encerrada'
    when c.status = 'ativo' and c.data_inicio is not null and c.data_inicio > now() then 'agendada'
    when c.status = 'ativo' then 'ativa'
    else c.status
  end as situacao,
  coalesce(sum(m.impressoes),0)::bigint as impressoes,
  coalesce(sum(m.cliques),0)::bigint as cliques,
  case when coalesce(sum(m.impressoes),0) = 0 then 0
       else round(sum(m.cliques)::numeric * 100 / sum(m.impressoes), 2) end as ctr,
  max(m.ultimo_clique) as ultimo_clique,
  max(m.ultima_visualizacao) as ultima_visualizacao
from public.campanhas_publicitarias c
left join public.publicidade_metricas_diarias m on m.campanha_id = c.id
group by c.id;

grant select on public.publicidade_resumo to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('publicidade','publicidade',true,15728640,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Midia publicidade publica" on storage.objects;
create policy "Midia publicidade publica" on storage.objects for select
using (bucket_id = 'publicidade');

drop policy if exists "Admins enviam midia publicidade" on storage.objects;
create policy "Admins enviam midia publicidade" on storage.objects for insert to authenticated
with check (bucket_id = 'publicidade' and public.is_admin());

drop policy if exists "Admins alteram midia publicidade" on storage.objects;
create policy "Admins alteram midia publicidade" on storage.objects for update to authenticated
using (bucket_id = 'publicidade' and public.is_admin()) with check (bucket_id = 'publicidade' and public.is_admin());

drop policy if exists "Admins excluem midia publicidade" on storage.objects;
create policy "Admins excluem midia publicidade" on storage.objects for delete to authenticated
using (bucket_id = 'publicidade' and public.is_admin());

-- Conversão compatível dos banners antigos. A origem é guardada para não duplicar.
do $$
begin
  if to_regclass('public.banners') is not null then
    execute $mig$
      insert into public.campanhas_publicitarias (
        nome, empresa_anunciante, tipo, imagem_url, video_url, link_destino,
        texto_botao, abrir_nova_aba, prioridade, status, data_inicio, data_fim,
        configuracao_futura
      )
      select
        coalesce(nullif(b.titulo,''),'Campanha importada'),
        coalesce(nullif(b.titulo,''),'Anunciante não informado'),
        case when b.video_url is not null and b.video_url <> '' then 'video' else 'banner' end,
        b.imagem_url, b.video_url, b.link_url, b.texto_botao, coalesce(b.nova_aba,true),
        coalesce(b.ordem,0), case when coalesce(b.ativo,false) then 'ativo' else 'pausado' end,
        b.inicio_em, b.fim_em, jsonb_build_object('banner_legado_id',b.id::text)
      from public.banners b
      where not exists (
        select 1 from public.campanhas_publicitarias c
        where c.configuracao_futura->>'banner_legado_id' = b.id::text
      )
    $mig$;

    execute $pos$
      insert into public.campanha_posicoes (campanha_id,posicao)
      select c.id,
        case b.posicao
          when 'home_topo' then 'home_topo'
          when 'home_meio' then 'home_entre_secoes'
          when 'home_rodape' then 'home_rodape'
          when 'noticias_topo' then 'noticias_topo'
          when 'noticias_meio' then 'noticias_entre_listagem'
          when 'noticia_individual_meio' then 'noticia_meio'
          when 'noticia_individual_final' then 'noticia_final'
          when 'guia_topo' then 'guia_topo'
          when 'guia_meio' then 'guia_entre_estabelecimentos'
          when 'turismo_topo' then 'turismo_topo'
          when 'turismo_meio' then 'turismo_entre_cartoes'
          when 'eventos_topo' then 'eventos_topo'
          else 'todas_paginas'
        end
      from public.campanhas_publicitarias c
      join public.banners b on c.configuracao_futura->>'banner_legado_id' = b.id::text
      on conflict do nothing
    $pos$;
  end if;
end $$;
