const SUPABASE_URL=process.env.SUPABASE_URL||"https://omhcpbphvtihqwdkbsbf.supabase.co";
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const roles=new Set(["super_admin","administrador","editor","redator","comercial","comunicacao","visualizador"]);
const jsonHeaders={"Content-Type":"application/json"};
function token(req){return String(req.headers.authorization||"").replace(/^Bearer\s+/i,"")}
async function auth(path,{method="GET",body,bearer=SERVICE_KEY}={}){const response=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${bearer}`,...jsonHeaders},body:body?JSON.stringify(body):undefined});const text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw Object.assign(new Error(data?.msg||data?.message||`Supabase Auth ${response.status}`),{status:response.status});return data}
async function rest(path,{method="GET",body,prefer="return=representation"}={}){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,Prefer:prefer,...jsonHeaders},body:body?JSON.stringify(body):undefined});const text=await response.text(),data=text?JSON.parse(text):null;if(!response.ok)throw Object.assign(new Error(data?.message||`Supabase ${response.status}`),{status:response.status});return data}
async function requireSuper(req){if(!SERVICE_KEY)throw Object.assign(new Error("SUPABASE_SERVICE_ROLE_KEY não configurada na Vercel."),{status:503});const access=token(req);if(!access)throw Object.assign(new Error("Sessão obrigatória."),{status:401});const user=await auth("user",{bearer:access});const rows=await rest(`usuarios_admin?id=eq.${encodeURIComponent(user.id)}&ativo=eq.true&funcao=eq.super_admin&select=id,email,funcao`);if(!rows?.length)throw Object.assign(new Error("Apenas Super Admin pode gerenciar usuários."),{status:403});return user}
async function activeSuperCount(){const rows=await rest("usuarios_admin?funcao=eq.super_admin&ativo=eq.true&select=id");return rows.length}
async function ensureCanChange(target,nextRole,nextActive,currentId){if(target.id===currentId&&nextActive===false)throw Object.assign(new Error("Você não pode desativar a própria conta."),{status:400});if(target.funcao==="super_admin"&&(nextRole!=="super_admin"||nextActive===false)&&await activeSuperCount()<=1)throw Object.assign(new Error("É obrigatório manter ao menos um Super Admin ativo."),{status:400})}
async function list(){const[profiles,authData,permissions]=await Promise.all([rest("usuarios_admin?select=id,nome,email,funcao,ativo,permissoes_extra,ultimo_login,criado_em,atualizado_em&order=criado_em.asc"),auth("admin/users?page=1&per_page=1000"),rest("admin_permissoes_funcao?select=funcao,modulo,acao&order=funcao,modulo,acao")]);const authUsers=new Map((authData.users||[]).map(user=>[user.id,user]));return{users:profiles.map(profile=>{const user=authUsers.get(profile.id)||{};return{...profile,ultimo_login:user.last_sign_in_at||profile.ultimo_login,auth_criado_em:user.created_at||profile.criado_em,email_confirmado:Boolean(user.email_confirmed_at)}}),permissions}}
async function create(body){const email=String(body.email||"").trim().toLowerCase(),password=String(body.password||""),nome=String(body.nome||"").trim(),funcao=String(body.funcao||"");if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error("Informe um e-mail válido."),{status:400});if(password.length<8)throw Object.assign(new Error("A senha temporária deve ter ao menos 8 caracteres."),{status:400});if(!nome||!roles.has(funcao))throw Object.assign(new Error("Nome e função são obrigatórios."),{status:400});const user=await auth("admin/users",{method:"POST",body:{email,password,email_confirm:true,user_metadata:{nome}}});try{await rest("usuarios_admin",{method:"POST",body:{id:user.id,email,nome,funcao,ativo:body.ativo!==false}})}catch(error){await auth(`admin/users/${user.id}`,{method:"DELETE"}).catch(()=>{});throw error}return{id:user.id}}
async function update(body,currentId){const id=String(body.id||""),rows=await rest(`usuarios_admin?id=eq.${encodeURIComponent(id)}&select=*`),target=rows?.[0];if(!target)throw Object.assign(new Error("Usuário não encontrado."),{status:404});const funcao=String(body.funcao||target.funcao),ativo=body.ativo!==false;if(!roles.has(funcao))throw Object.assign(new Error("Função inválida."),{status:400});await ensureCanChange(target,funcao,ativo,currentId);const authPayload={};if(body.email&&String(body.email).trim().toLowerCase()!==target.email)authPayload.email=String(body.email).trim().toLowerCase();if(body.password){if(String(body.password).length<8)throw Object.assign(new Error("A nova senha deve ter ao menos 8 caracteres."),{status:400});authPayload.password=String(body.password)}if(body.nome)authPayload.user_metadata={nome:String(body.nome).trim()};if(Object.keys(authPayload).length)await auth(`admin/users/${id}`,{method:"PUT",body:authPayload});await rest(`usuarios_admin?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:{nome:String(body.nome||target.nome).trim(),email:authPayload.email||target.email,funcao,ativo}});return{id}}
async function remove(body,currentId){const id=String(body.id||"");if(id===currentId)throw Object.assign(new Error("Você não pode excluir a própria conta."),{status:400});const rows=await rest(`usuarios_admin?id=eq.${encodeURIComponent(id)}&select=*`),target=rows?.[0];if(!target)throw Object.assign(new Error("Usuário não encontrado."),{status:404});await ensureCanChange(target,target.funcao,false,currentId);await auth(`admin/users/${id}`,{method:"DELETE"});return{id}}
module.exports=async(req,res)=>{try{const current=await requireSuper(req);if(req.method==="GET")return res.status(200).json(await list());if(req.method==="POST")return res.status(201).json(await create(req.body||{}));if(req.method==="PATCH")return res.status(200).json(await update(req.body||{},current.id));if(req.method==="DELETE")return res.status(200).json(await remove(req.body||{},current.id));return res.status(405).json({error:"Método não permitido"})}catch(error){console.error("admin-users:",error.message);return res.status(error.status||500).json({error:error.message||"Falha ao gerenciar usuários."})}};
