const URL = process.env.SUPABASE_URL || 'https://omhcpbphvtihqwdkbsbf.supabase.co';
const KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_m02B2sC8Ddh4fCtnvsGePg_TqwUanoM';
const DOMAIN = 'https://euamourania.com.br';
const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
module.exports = async function handler(req, res) {
  const slug = String(req.query.slug || '');
  const response = await fetch(`${URL}/rest/v1/iniciativas_comunitarias?select=*&slug=eq.${encodeURIComponent(slug)}&status=eq.publicado&limit=1`, { headers: { apikey: KEY } });
  const [item] = await response.json().catch(() => []);
  if (!response.ok || !item) return res.status(404).send('Iniciativa não encontrada');
  const [helpResponse, actionsResponse] = await Promise.all([
    fetch(`${URL}/rest/v1/iniciativas_formas_ajuda?select=*&iniciativa_id=eq.${encodeURIComponent(item.id)}&ativo=eq.true&order=ordem.asc`, { headers: { apikey: KEY } }),
    fetch(`${URL}/rest/v1/iniciativas_comunitarias?select=id,titulo,slug,resumo,imagem_capa_url&iniciativa_pai_id=eq.${encodeURIComponent(item.id)}&status=eq.publicado&order=atualizado_em.desc`, { headers: { apikey: KEY } })
  ]);
  const help = helpResponse.ok ? await helpResponse.json().catch(() => []) : [];
  const actions = actionsResponse.ok ? await actionsResponse.json().catch(() => []) : [];
  const canonical = `${DOMAIN}/iniciativas/${encodeURIComponent(item.slug)}`, title = `${item.titulo} | Iniciativas da Comunidade`, description = String(item.resumo || item.descricao || 'Iniciativa da comunidade de Urânia.').replace(/<[^>]*>/g, '').slice(0, 160), image = item.imagem_capa_url || `${DOMAIN}/assets/1505%20-%20Urania%20-%20Logo%20Horizontal%20-%201.png`;
  const safeHref = value => { try { const url = new URL(value); return /^https?:$/.test(url.protocol) ? url.href : '#'; } catch { return '#'; } };
  const contactLinks = [item.whatsapp && `<a href="https://wa.me/${esc(String(item.whatsapp).replace(/\D/g,''))}" target="_blank" rel="noopener">WhatsApp</a>`, item.telefone && `<a href="tel:${esc(String(item.telefone).replace(/\D/g,''))}">Telefone</a>`, item.email && `<a href="mailto:${esc(item.email)}">E-mail</a>`, item.site_url && `<a href="${esc(safeHref(item.site_url))}" target="_blank" rel="noopener">Site</a>`, item.instagram && `<a href="${esc(safeHref(item.instagram.startsWith('http') ? item.instagram : `https://instagram.com/${item.instagram.replace(/^@/,'')}`))}" target="_blank" rel="noopener">Instagram</a>`].filter(Boolean).join(' · ');
  const helpHtml = help.length ? `<section><h2>Como ajudar</h2>${help.map(entry => `<article class="card"><h3>${esc(entry.titulo)}</h3>${entry.descricao ? `<p>${esc(entry.descricao)}</p>` : ''}${entry.tipo === 'pix' ? `<p><strong>Recebedor: ${esc(entry.recebedor_nome)}</strong></p><button type="button" data-pix="${esc(entry.valor_publico)}">Copiar chave Pix</button>` : entry.valor_publico ? `<a href="${esc(entry.tipo === 'telefone' ? `tel:${String(entry.valor_publico).replace(/\D/g,'')}` : entry.tipo === 'whatsapp' ? `https://wa.me/${String(entry.valor_publico).replace(/\D/g,'')}` : safeHref(entry.valor_publico))}" target="_blank" rel="noopener">Acessar</a>` : ''}</article>`).join('')}<p><small>O Eu Amo Urânia apenas divulga esta iniciativa e não processa transferências. Confira os dados antes de pagar.</small></p></section>` : '';
  const actionsHtml = actions.length ? `<section><h2>Ações desta iniciativa</h2>${actions.map(action => `<article class="card"><h3><a href="/iniciativas/${encodeURIComponent(action.slug)}">${esc(action.titulo)}</a></h3><p>${esc(action.resumo || '')}</p></article>`).join('')}</section>` : '';
  res.setHeader('Content-Type','text/html; charset=utf-8'); res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=86400');
  return res.status(200).send(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Eu Amo Urânia"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(image)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}"><link rel="stylesheet" href="/styles.css"></head><body><main class="container"><a href="/iniciativas/">← Iniciativas da Comunidade</a><img src="${esc(image)}" alt="" style="width:100%;max-height:420px;object-fit:cover;border-radius:24px;margin-top:24px"><p>Comunidade</p><h1>${esc(item.titulo)}</h1><p>${esc(item.resumo || '')}</p><h2>Sobre</h2><p>${esc(item.descricao || '')}</p>${contactLinks ? `<section><h2>Contatos e redes</h2><p>${contactLinks}</p></section>` : ''}${helpHtml}${actionsHtml}</main><script>document.addEventListener('click',function(e){var b=e.target.closest('[data-pix]');if(!b)return;navigator.clipboard.writeText(b.dataset.pix).then(function(){b.textContent='Chave Pix copiada';});});</script></body></html>`);
}
