const SUPABASE_URL=process.env.SUPABASE_URL||"https://omhcpbphvtihqwdkbsbf.supabase.co";
const SUPABASE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY||"sb_publishable_m02B2sC8Ddh4fCtnvsGePg_TqwUanoM";
const DEFAULT_DOMAIN="https://euamourania.com.br";
const DEFAULT_LOGO="/assets/1505%20-%20Urania%20-%20Logo%20Horizontal%20-%201.png";
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const validDomain=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.origin:DEFAULT_DOMAIN}catch{return DEFAULT_DOMAIN}};
const absolute=(v,domain,fallback=DEFAULT_LOGO)=>{try{return new URL(v||fallback,`${domain}/`).href}catch{return new URL(fallback,`${domain}/`).href}};
async function rest(path,{method="GET",body,token}={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"return=representation"},body:body?JSON.stringify(body):undefined});const text=await r.text();if(!r.ok)throw new Error(JSON.parse(text||"{}").message||`Supabase ${r.status}`);return text?JSON.parse(text):null}
async function podeEnviar(token){if(!token)return false;try{return await rest("rpc/tem_permissao_admin",{method:"POST",token,body:{p_modulo:"comunicacao",p_acao:"enviar"}})===true}catch{return false}}
async function getBranding(){
  try{
    const keys="nome_site,logo_cabecalho,dominio_principal,rodape_texto,imagem_compartilhamento";
    const rows=await rest(`configuracoes_site?select=chave,valor&chave=in.(${keys})`);
    const config=Object.fromEntries((rows||[]).map(item=>[item.chave,item.valor]));
    const domain=validDomain(config.dominio_principal||DEFAULT_DOMAIN);
    return{domain,name:config.nome_site||"Eu Amo Urânia",logo:absolute(config.logo_cabecalho||config.imagem_compartilhamento,domain),footer:config.rodape_texto||"Você recebeu este e-mail porque se cadastrou no Eu Amo Urânia."};
  }catch{return{domain:DEFAULT_DOMAIN,name:"Eu Amo Urânia",logo:absolute(DEFAULT_LOGO,DEFAULT_DOMAIN),footer:"Você recebeu este e-mail porque se cadastrou no Eu Amo Urânia."}}
}
function template(n,s,brand){const token=s.token_descadastro,open=`${brand.domain}/api/newsletter-open?c=${n.id}&t=${token}`,target=/^https?:\/\//i.test(n.link_botao||"")?n.link_botao:"",click=target?`${brand.domain}/api/newsletter-click?c=${n.id}&t=${token}&url=${encodeURIComponent(target)}`:"",image=/^https?:\/\//i.test(n.imagem_url||"")?`<img src="${esc(n.imagem_url)}" alt="" style="display:block;width:100%;max-height:360px;object-fit:cover">`:"",button=click?`<p style="margin:28px 0"><a href="${esc(click)}" style="display:inline-block;padding:13px 22px;background:#0b4f6c;color:#fff;text-decoration:none;border-radius:999px;font-weight:700">${esc(n.texto_botao||"Saiba mais")}</a></p>`:"";return`<!doctype html><html><body style="margin:0;background:#f3f6f7;font-family:Arial,sans-serif;color:#073b4c"><div style="display:none;max-height:0;overflow:hidden">${esc(n.preheader||"")}</div><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table width="620" style="width:100%;max-width:620px;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="padding:22px 28px;text-align:center"><img src="${esc(brand.logo)}" width="190" alt="${esc(brand.name)}"></td></tr><tr><td>${image}</td></tr><tr><td style="padding:28px"><p style="margin:0 0 8px;color:#1385a5;font-size:12px;font-weight:700;letter-spacing:1.5px">${esc(brand.name.toUpperCase())}</p><h1 style="margin:0 0 18px;font-size:28px;line-height:1.2">${esc(n.titulo)}</h1><div style="font-size:16px;line-height:1.65;color:#405b65">${n.conteudo_html}</div>${button}</td></tr><tr><td style="padding:22px 28px;background:#073b4c;color:#d9e6ea;text-align:center;font-size:12px">${esc(brand.footer)}<br><a href="${brand.domain}/descadastrar.html?token=${token}" style="color:#fff">Cancelar inscrição</a></td></tr></table><img src="${open}" width="1" height="1" alt="" style="display:block"></td></tr></table></body></html>`}
module.exports=async(req,res)=>{if(req.method!=="POST")return res.status(405).json({error:"Método não permitido"});const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!await podeEnviar(token))return res.status(403).json({error:"Permissão para enviar newsletters necessária"});if(!process.env.BREVO_API_KEY)return res.status(503).json({error:"BREVO_API_KEY não configurada na Vercel"});try{const{id,action="send",testEmail}=req.body||{},[news,brand]=await Promise.all([(await rest(`newsletters?id=eq.${encodeURIComponent(id)}&select=*`,{token}))?.[0],getBranding()]);if(!news)return res.status(404).json({error:"Newsletter não encontrada"});let subscribers=[];if(action==="test"){if(!/^\S+@\S+\.\S+$/.test(testEmail||""))return res.status(400).json({error:"Informe um e-mail de teste válido"});subscribers=[{id:null,nome:"Leitor de teste",email:testEmail,token_descadastro:"00000000-0000-0000-0000-000000000000"}]}else{const all=await rest("newsletter_assinantes?status=eq.ativo&select=id,nome,email,interesses,token_descadastro&order=cadastrado_em.asc",{token}),targets=news.interesses_alvo||["tudo"];subscribers=all.filter(s=>targets.includes("tudo")||s.interesses?.includes("tudo")||s.interesses?.some(x=>targets.includes(x)));if(!subscribers.length)return res.status(400).json({error:"Nenhum assinante ativo para este público"})}const messageIds=[];for(let i=0;i<subscribers.length;i+=500){const chunk=subscribers.slice(i,i+500),payload={sender:{name:brand.name,email:process.env.BREVO_SENDER_EMAIL||"euamourania@gmail.com"},subject:news.assunto,htmlContent:template(news,chunk[0],brand),messageVersions:chunk.map(s=>({to:[{email:s.email,name:s.nome||undefined}],htmlContent:template(news,s,brand)})),tags:[`newsletter-${news.id}`]};if(action==="schedule"&&news.agendado_em)payload.scheduledAt=new Date(news.agendado_em).toISOString();const br=await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{"api-key":process.env.BREVO_API_KEY,"Content-Type":"application/json",accept:"application/json"},body:JSON.stringify(payload)}),data=await br.json();if(!br.ok)throw new Error(data.message||`Brevo ${br.status}`);messageIds.push(...(data.messageIds||[data.messageId]))}if(action!=="test"){await rest(`newsletter_envios?on_conflict=newsletter_id,assinante_id`,{method:"POST",token,body:subscribers.map((s,i)=>({newsletter_id:news.id,assinante_id:s.id,brevo_message_id:messageIds[i]||null,status:action==="schedule"?"agendado":"enviado"}))});await rest(`newsletters?id=eq.${news.id}`,{method:"PATCH",token,body:{status:action==="schedule"?"agendado":"enviado",total_enviados:subscribers.length,enviado_em:action==="schedule"?null:new Date().toISOString()}})}return res.status(200).json({ok:true,total:subscribers.length,message:action==="test"?"Teste enviado.":action==="schedule"?"Envio agendado.":"Newsletter enviada."})}catch(e){console.error(e);return res.status(500).json({error:e.message||"Falha no envio"})}};
