const SUPABASE_URL="https://omhcpbphvtihqwdkbsbf.supabase.co";
const SUPABASE_KEY="sb_publishable_m02B2sC8Ddh4fCtnvsGePg_TqwUanoM";
const DOMAIN="https://euamourania.com.br";
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const plain=(v="")=>String(v).replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const absolute=v=>{if(!v)return `${DOMAIN}/assets/Design%20sem%20nome%20(9).png`;try{return new URL(v,DOMAIN+"/").href}catch{return `${DOMAIN}/assets/Design%20sem%20nome%20(9).png`}};
module.exports=async(req,res)=>{
  const slug=String(req.query.slug||"").trim();
  if(!/^[a-z0-9-]+$/.test(slug)){res.status(404).send("Notícia não encontrada");return}
  try{
    const endpoint=`${SUPABASE_URL}/rest/v1/noticias?slug=eq.${encodeURIComponent(slug)}&status=eq.publicado&select=*&limit=1`;
    const response=await fetch(endpoint,{headers:{apikey:SUPABASE_KEY}}),rows=await response.json(),n=rows?.[0];
    if(!response.ok||!n){res.status(404).send("Notícia não encontrada");return}
    const canonical=`${DOMAIN}/noticias/${encodeURIComponent(n.slug)}`,description=(n.seo_descricao||n.resumo||plain(n.conteudo_html)).slice(0,160),image=absolute(n.seo_imagem||n.imagem_url),title=`${n.seo_titulo||n.titulo} | Eu Amo Urânia`;
    const structured=JSON.stringify({"@context":"https://schema.org","@type":"NewsArticle",headline:n.titulo,description,image:[image],datePublished:n.publicado_em,dateModified:n.atualizado_em||n.publicado_em,author:{"@type":"Organization",name:n.autor||"Eu Amo Urânia"},publisher:{"@type":"Organization",name:"Eu Amo Urânia",logo:{"@type":"ImageObject",url:`${DOMAIN}/assets/Design%20sem%20nome%20(9).png`}},mainEntityOfPage:canonical}).replace(/</g,"\\u003c");
    res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Cache-Control","public, s-maxage=300, stale-while-revalidate=86400");
    res.status(200).send(`<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:site_name" content="Eu Amo Urânia"><meta property="og:title" content="${esc(n.titulo)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(image)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(n.titulo)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}"><meta name="theme-color" content="#0b4f6c"><script type="application/ld+json">${structured}</script><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/inner-pages.css"><link rel="icon" href="/assets/Design sem nome (9).png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/dompurify@3.2.6/dist/purify.min.js" defer></script></head><body class="inner-page"><a class="skip-link" href="#newsDetails">Pular para a notícia</a><header class="site-header"><div class="container header-content"><a class="brand" href="/index.html"><img src="/assets/1505 - Urania - Logo Horizontal - 1.png" alt="Eu Amo Urânia" width="190" height="56"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="menu-principal"><span class="menu-icon" aria-hidden="true"></span><span>Menu</span></button><nav class="main-nav" id="menu-principal"><ul><li><a href="/index.html">Início</a></li><li><a href="/guia.html">Guia da cidade</a></li><li><a href="/turismo.html">Turismo</a></li><li><a href="/news/" aria-current="page">Notícias</a></li><li><a href="/quem-somos.html">Quem somos</a></li></ul></nav></div></header><main id="newsDetails" class="article-main" aria-live="polite"><p class="not-found-message">Carregando notícia…</p></main><footer class="site-footer"><div class="container footer-grid"><div><img src="/assets/1505 - Urania - Logo Horizontal - 1.png" alt="Eu Amo Urânia" class="footer-logo"><p>Informação, turismo e comunidade.</p></div><nav><a href="mailto:euamourania@gmail.com">Contato</a><a href="/termos-de-servico.html">Termos</a><a href="/politica-de-privacidade.html">Privacidade</a></nav></div><div class="container footer-bottom"><p>&copy; <span id="year"></span> Eu Amo Urânia.</p></div></footer><script src="/script.js"></script><script type="module" src="/assets/js/pages/noticia-page.js"></script></body></html>`);
  }catch(error){console.error(error);res.status(500).send("Não foi possível carregar a notícia")}
};
